#ifndef HW_OPENTITAN_SPI_HOST_QP_SHIM_H
#define HW_OPENTITAN_SPI_HOST_QP_SHIM_H

#include "qom/object.h"

#define TYPE_OT_SPI_HOST_QP "ot-spi-host-qp"
OBJECT_DECLARE_SIMPLE_TYPE(OtSPIHostQpState, OT_SPI_HOST_QP)

#endif /* HW_OPENTITAN_SPI_HOST_QP_SHIM_H */
