#ifndef HW_OPENTITAN_ALERT_HANDLER_QP_SHIM_H
#define HW_OPENTITAN_ALERT_HANDLER_QP_SHIM_H

#include "qom/object.h"

#define TYPE_OT_ALERT_HANDLER_QP "ot-alert-handler-qp"
OBJECT_DECLARE_SIMPLE_TYPE(OtAlertHandlerQpState, OT_ALERT_HANDLER_QP)

#endif /* HW_OPENTITAN_ALERT_HANDLER_QP_SHIM_H */
