#ifndef HW_OPENTITAN_AON_TIMER_QP_SHIM_H
#define HW_OPENTITAN_AON_TIMER_QP_SHIM_H

#include "qom/object.h"

#define TYPE_OT_AON_TIMER_QP "ot-aon-timer-qp"
OBJECT_DECLARE_SIMPLE_TYPE(OtAonTimerQpState, OT_AON_TIMER_QP)

#endif /* HW_OPENTITAN_AON_TIMER_QP_SHIM_H */
