/*
 * QEMU OpenTitan GPIO device — qemu-passes shim
 *
 * Frontend wrapper around the auto-generated GPIO model from
 *   hw/opentitan/qemu_passes/gpio.{c,h}
 *
 * Purpose: present the OtGPIO-shaped QOM interface that
 * hw/riscv/ot_earlgrey.c expects (32 per-pin IRQs + alert + the same
 * properties as ot_gpio_eg.c), so the SoC table can carry
 * .type = TYPE_OT_GPIO_QP for GPIO without further changes elsewhere.
 *
 * MMIO read/write callbacks delegate to the generated entrypoints
 * gpio_read() / gpio_write().  The QEMU backend interface (chardev,
 * IRQ wires, ptimer, ...) is intentionally NOT wired here — this is
 * the "frontend only" milestone: prove that the auto-generated model
 * can be instantiated by Earl Grey and that firmware boots through
 * the device.  Backend hookup is a later milestone.
 */

#include "qemu/osdep.h"
#include "qemu/log.h"
#include "qemu/module.h"
#include "qapi/error.h"
#include "chardev/char-fe.h"
#include "hw/sysbus.h"
#include "hw/qdev-properties.h"
#include "hw/qdev-properties-system.h"
#include "hw/irq.h"
#include "hw/opentitan/ot_alert.h"
#include "hw/opentitan/ot_common.h"
#include "hw/opentitan/ot_gpio_qp.h"
#include "hw/riscv/ibex_irq.h"

/* Generated by qemu-passes from gpio_llhd.mlir.
 * Declares gpio_state, gpio_read(), gpio_write().
 *
 * The header also defines `TYPE_GPIO` and `GPIO(obj)` for its own
 * internal QOM use; those don't conflict with QEMU because the names
 * are distinct from anything we use here, and the symbols are only
 * referenced inside the generated translation unit.  No #undef needed. */
#include "qemu_passes/gpio.h"

/* 32 GPIO pin IRQs, mirroring ot_gpio_eg.c — Earl Grey SoC table wires
 * 32 sysbus IRQs from this device into PLIC sources 37-68. */
#define OT_GPIO_QP_IRQ_NUM 32u

struct OtGpioQpState {
    SysBusDevice parent_obj;
    MemoryRegion mmio;
    IbexIRQ irqs[OT_GPIO_QP_IRQ_NUM];
    IbexIRQ alert;

    /* Properties mirror ot_gpio_eg.c so the Earl Grey QOM framework can
     * pass through any reset-value / chardev / wipe options it sets on
     * the upstream GPIO model.  We accept-but-ignore the values: the
     * generated model has its own initial state and no chardev wiring. */
    char *ot_id;
    uint32_t reset_in;
    uint32_t reset_out;
    uint32_t reset_oe;
    bool wipe;
    CharFrontend chr;

    /* Embedded auto-generated device state. */
    gpio_state core;
};

OBJECT_DEFINE_SIMPLE_TYPE(OtGpioQpState, ot_gpio_qp, OT_GPIO_QP, SYS_BUS_DEVICE)

static uint64_t ot_gpio_qp_read(void *opaque, hwaddr addr, unsigned size)
{
    OtGpioQpState *s = OT_GPIO_QP(opaque);
    return gpio_read(&s->core, addr, size);
}

static void ot_gpio_qp_write(void *opaque, hwaddr addr, uint64_t value,
                             unsigned size)
{
    OtGpioQpState *s = OT_GPIO_QP(opaque);
    gpio_write(&s->core, addr, value, size);
}

static const MemoryRegionOps ot_gpio_qp_ops = {
    .read = ot_gpio_qp_read,
    .write = ot_gpio_qp_write,
    .endianness = DEVICE_LITTLE_ENDIAN,
    .impl.min_access_size = 4,
    .impl.max_access_size = 4,
};

static const Property ot_gpio_qp_properties[] = {
    DEFINE_PROP_STRING(OT_COMMON_DEV_ID, OtGpioQpState, ot_id),
    DEFINE_PROP_UINT32("in",  OtGpioQpState, reset_in,  0u),
    DEFINE_PROP_UINT32("out", OtGpioQpState, reset_out, 0u),
    DEFINE_PROP_UINT32("oe",  OtGpioQpState, reset_oe,  0u),
    DEFINE_PROP_BOOL("wipe",  OtGpioQpState, wipe, false),
    DEFINE_PROP_CHR("chardev", OtGpioQpState, chr),
};

static void ot_gpio_qp_realize(DeviceState *dev, Error **errp)
{
    /* Backend hookup intentionally absent: chardev handlers, IRQ wiring
     * to GPIO pin level, etc. all stay unconnected.  Frontend-only
     * milestone — let Earl Grey instantiate the device and let MMIO
     * accesses reach the generated logic. */
    (void)dev;
    (void)errp;
}

static void ot_gpio_qp_init(Object *obj)
{
    OtGpioQpState *s = OT_GPIO_QP(obj);

    for (unsigned i = 0; i < OT_GPIO_QP_IRQ_NUM; i++) {
        ibex_sysbus_init_irq(obj, &s->irqs[i]);
    }
    ibex_qdev_init_irq(obj, &s->alert, OT_DEVICE_ALERT);

    memory_region_init_io(&s->mmio, obj, &ot_gpio_qp_ops, s,
                          TYPE_OT_GPIO_QP, 0x1000);
    sysbus_init_mmio(SYS_BUS_DEVICE(obj), &s->mmio);

    /* Out-of-reset.  See ot_uart_qp.c for the same comment — generated
     * model gates writes on `!rst_ni`, so park rst_ni high or every
     * register stays at its init value. */
    s->core.rst_ni = 1;
}

static void ot_gpio_qp_finalize(Object *obj)
{
    (void)obj;
}

static void ot_gpio_qp_class_init(ObjectClass *klass, const void *data)
{
    DeviceClass *dc = DEVICE_CLASS(klass);
    (void)data;

    dc->realize = ot_gpio_qp_realize;
    device_class_set_props(dc, ot_gpio_qp_properties);
    set_bit(DEVICE_CATEGORY_INPUT, dc->categories);
}
