#ifndef HW_OPENTITAN_SYSRST_CTRL_QP_SHIM_H
#define HW_OPENTITAN_SYSRST_CTRL_QP_SHIM_H

#include "qom/object.h"

#define TYPE_OT_SYSRST_CTRL_QP "ot-sysrst-ctrl-qp"
OBJECT_DECLARE_SIMPLE_TYPE(OtSysrstCtrlQpState, OT_SYSRST_CTRL_QP)

#endif /* HW_OPENTITAN_SYSRST_CTRL_QP_SHIM_H */
