#ifndef AON_TIMER_H
#define AON_TIMER_H

#include "hw/sysbus.h"
#include "qom/object.h"

#define TYPE_AON_TIMER "aon_timer"
#define AON_TIMER(obj) OBJECT_CHECK(aon_timer_state, (obj), TYPE_AON_TIMER)

typedef struct {
    /* <private> */
    SysBusDevice parent_obj;

    /* <public> */
    MemoryRegion mmio;

    /* ---- Bus Interface Ports (BIP) ---- */
    /* These signals bridge QEMU MMIO and internal logic. */
    uint32_t reg_rdata_next;  /* BIP, 32-bit */
    uint8_t reg_we;  /* BIP, 1-bit */
    uint32_t tl_i_a_address;  /* BIP, 32-bit */
    uint8_t tl_i_a_user_instr_type;  /* BIP, 4-bit */
    uint32_t u_reg_if_wdata_o;  /* BIP, 32-bit */

    /* ---- Internal state registers ---- */
    uint8_t alert_rx_i_0__ack_n;  /* 1-bit */
    uint8_t alert_rx_i_0__ack_p;  /* 1-bit */
    uint8_t alert_rx_i_0__ping_n;  /* 1-bit */
    uint8_t alert_rx_i_0__ping_p;  /* 1-bit */
    uint8_t alert_tx_o_0__alert_n;  /* 1-bit */
    uint8_t alert_tx_o_0__alert_p;  /* 1-bit */
    uint8_t alerts;  /* 1-bit */
    uint8_t aon_rst_req_d;  /* 1-bit */
    uint8_t aon_rst_req_q;  /* 1-bit */
    uint8_t aon_timer_rst_req_o;  /* 1-bit */
    uint8_t clk_aon_i;  /* 1-bit */
    uint8_t clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_ack_level;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_ack_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_clr;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_nd;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_pd;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_req_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_rx_i_ack_n;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_rx_i_ack_p;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_rx_i_ping_n;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_rx_i_ping_p;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_set_d;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_set_q;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_state_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_test_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_test_set_d;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_test_set_q;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_test_trigger;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_trigger;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_tx_o_alert_n;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_tx_o_alert_p;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_ping_clr;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_ping_set_d;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_ping_set_q;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_ping_trigger;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_sigint_detected;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_state_d;  /* 3-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_state_q;  /* 3-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_diff_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_diff_pi;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_event_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_fall_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_diff_check_ok;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_diff_n_edge;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_diff_nd;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_diff_nq;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_diff_p_edge;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_diff_pd;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_diff_pq;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_d_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_u_sync_1_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_u_sync_1_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_u_sync_1_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_u_sync_1_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_u_sync_2_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_u_sync_2_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_u_sync_2_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_u_sync_2_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_d_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_u_sync_1_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_u_sync_1_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_u_sync_1_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_u_sync_1_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_u_sync_2_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_u_sync_2_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_u_sync_2_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_u_sync_2_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_level;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_skew_cnt_d;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_skew_cnt_q;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_state_d;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_state_q;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_level_d;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_level_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_level_q;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_rise_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_sigint_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_diff_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_diff_pi;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_event_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_fall_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_diff_check_ok;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_diff_n_edge;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_diff_nd;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_diff_nq;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_diff_p_edge;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_diff_pd;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_diff_pq;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_d_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_u_sync_1_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_u_sync_1_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_u_sync_1_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_u_sync_1_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_u_sync_2_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_u_sync_2_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_u_sync_2_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_u_sync_2_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_d_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_u_sync_1_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_u_sync_1_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_u_sync_1_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_u_sync_1_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_u_sync_2_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_u_sync_2_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_u_sync_2_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_u_sync_2_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_level;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_skew_cnt_d;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_skew_cnt_q;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_state_d;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_state_q;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_level_d;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_level_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_level_q;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_rise_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_sigint_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_ack_in_i;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_ack_out_o;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_ack_u_secure_anchor_buf_in_i;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_ack_u_secure_anchor_buf_out_o;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_in_req_in_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_in_req_out_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_in_req_u_secure_anchor_buf_in_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_in_req_u_secure_anchor_buf_out_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_ping_in_i;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_ping_out_o;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_ping_u_secure_anchor_buf_in_i;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_ping_u_secure_anchor_buf_out_o;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_flop_alert_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_flop_alert_d_i;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_flop_alert_q_o;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_flop_alert_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_flop_alert_u_secure_anchor_flop_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_flop_alert_u_secure_anchor_flop_d_i;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_flop_alert_u_secure_anchor_flop_q_o;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_flop_alert_u_secure_anchor_flop_rst_ni;  /* 1-bit */
    uint8_t hw2reg_intr_state_wdog_timer_bark_d;  /* 1-bit */
    uint8_t hw2reg_intr_state_wdog_timer_bark_de;  /* 1-bit */
    uint8_t hw2reg_intr_state_wkup_timer_expired_d;  /* 1-bit */
    uint8_t hw2reg_intr_state_wkup_timer_expired_de;  /* 1-bit */
    uint32_t hw2reg_wdog_count_d;  /* 32-bit */
    uint8_t hw2reg_wdog_count_de;  /* 1-bit */
    uint8_t hw2reg_wkup_cause_d;  /* 1-bit */
    uint8_t hw2reg_wkup_cause_de;  /* 1-bit */
    uint32_t hw2reg_wkup_count_hi_d;  /* 32-bit */
    uint8_t hw2reg_wkup_count_hi_de;  /* 1-bit */
    uint32_t hw2reg_wkup_count_lo_d;  /* 32-bit */
    uint8_t hw2reg_wkup_count_lo_de;  /* 1-bit */
    uint8_t intr_state_q;  /* 2-bit */
    uint8_t intr_test_q;  /* 2-bit */
    uint8_t intr_wdog_timer_bark_o;  /* 1-bit */
    uint8_t intr_wkup_timer_expired_o;  /* 1-bit */
    uint8_t lc_escalate_en_i;  /* 4-bit */
    uint8_t nmi_wdog_timer_bark_o;  /* 1-bit */
    uint8_t racl_error_o_ctn_uid;  /* 1-bit */
    uint8_t racl_error_o_overflow;  /* 1-bit */
    uint8_t racl_error_o_racl_role;  /* 1-bit */
    uint8_t racl_error_o_read_access;  /* 1-bit */
    uint32_t racl_error_o_request_address;  /* 32-bit */
    uint8_t racl_error_o_valid;  /* 1-bit */
    uint8_t racl_policies_i_0__read_perm;  /* 2-bit */
    uint8_t racl_policies_i_0__write_perm;  /* 2-bit */
    uint8_t rst_aon_ni;  /* 1-bit */
    uint8_t rst_ni;  /* 1-bit */
    uint8_t sleep_mode_i;  /* 1-bit */
    uint32_t tl_i_a_data;  /* 32-bit */
    uint8_t tl_i_a_mask;  /* 4-bit */
    uint8_t tl_i_a_opcode;  /* 3-bit */
    uint8_t tl_i_a_param;  /* 3-bit */
    uint8_t tl_i_a_size;  /* 2-bit */
    uint8_t tl_i_a_source;  /* 8-bit */
    uint8_t tl_i_a_user_cmd_intg;  /* 7-bit */
    uint8_t tl_i_a_user_data_intg;  /* 7-bit */
    uint8_t tl_i_a_user_rsvd;  /* 5-bit */
    uint8_t tl_i_a_valid;  /* 1-bit */
    uint8_t tl_i_d_ready;  /* 1-bit */
    uint8_t tl_o_a_ready;  /* 1-bit */
    uint32_t tl_o_d_data;  /* 32-bit */
    uint8_t tl_o_d_error;  /* 1-bit */
    uint8_t tl_o_d_opcode;  /* 3-bit */
    uint8_t tl_o_d_param;  /* 3-bit */
    uint8_t tl_o_d_sink;  /* 1-bit */
    uint8_t tl_o_d_size;  /* 2-bit */
    uint8_t tl_o_d_source;  /* 8-bit */
    uint8_t tl_o_d_user_data_intg;  /* 7-bit */
    uint8_t tl_o_d_user_rsp_intg;  /* 7-bit */
    uint8_t tl_o_d_valid;  /* 1-bit */
    uint8_t u_aon_intr_flop_clk_i;  /* 1-bit */
    uint8_t u_aon_intr_flop_d_i;  /* 2-bit */
    uint8_t u_aon_intr_flop_q_o;  /* 2-bit */
    uint8_t u_aon_intr_flop_rst_ni;  /* 1-bit */
    uint8_t u_core_clk_aon_i;  /* 1-bit */
    uint8_t u_core_lc_escalate_en_i_0_;  /* 4-bit */
    uint8_t u_core_lc_escalate_en_i_1_;  /* 4-bit */
    uint8_t u_core_lc_escalate_en_i_2_;  /* 4-bit */
    uint16_t u_core_prescale_count_d;  /* 12-bit */
    uint16_t u_core_prescale_count_q;  /* 12-bit */
    uint8_t u_core_prescale_en;  /* 1-bit */
    uint8_t u_core_reg2hw_i_alert_test_q;  /* 1-bit */
    uint8_t u_core_reg2hw_i_alert_test_qe;  /* 1-bit */
    uint8_t u_core_reg2hw_i_intr_state_wdog_timer_bark_q;  /* 1-bit */
    uint8_t u_core_reg2hw_i_intr_state_wkup_timer_expired_q;  /* 1-bit */
    uint8_t u_core_reg2hw_i_intr_test_wdog_timer_bark_q;  /* 1-bit */
    uint8_t u_core_reg2hw_i_intr_test_wdog_timer_bark_qe;  /* 1-bit */
    uint8_t u_core_reg2hw_i_intr_test_wkup_timer_expired_q;  /* 1-bit */
    uint8_t u_core_reg2hw_i_intr_test_wkup_timer_expired_qe;  /* 1-bit */
    uint32_t u_core_reg2hw_i_wdog_bark_thold_q;  /* 32-bit */
    uint32_t u_core_reg2hw_i_wdog_bite_thold_q;  /* 32-bit */
    uint32_t u_core_reg2hw_i_wdog_count_q;  /* 32-bit */
    uint8_t u_core_reg2hw_i_wdog_ctrl_enable_q;  /* 1-bit */
    uint8_t u_core_reg2hw_i_wdog_ctrl_pause_in_sleep_q;  /* 1-bit */
    uint8_t u_core_reg2hw_i_wkup_cause_q;  /* 1-bit */
    uint32_t u_core_reg2hw_i_wkup_count_hi_q;  /* 32-bit */
    uint32_t u_core_reg2hw_i_wkup_count_lo_q;  /* 32-bit */
    uint8_t u_core_reg2hw_i_wkup_ctrl_enable_q;  /* 1-bit */
    uint16_t u_core_reg2hw_i_wkup_ctrl_prescaler_q;  /* 12-bit */
    uint8_t u_core_reg2hw_i_wkup_ctrl_prescaler_qe;  /* 1-bit */
    uint32_t u_core_reg2hw_i_wkup_thold_hi_q;  /* 32-bit */
    uint32_t u_core_reg2hw_i_wkup_thold_lo_q;  /* 32-bit */
    uint8_t u_core_rst_aon_ni;  /* 1-bit */
    uint8_t u_core_sleep_mode_i;  /* 1-bit */
    uint8_t u_core_wdog_count_reg_wr_o;  /* 1-bit */
    uint32_t u_core_wdog_count_wr_data_o;  /* 32-bit */
    uint8_t u_core_wdog_intr_o;  /* 1-bit */
    uint8_t u_core_wdog_reset_req_o;  /* 1-bit */
    uint8_t u_core_wkup_count_reg_wr_o;  /* 1-bit */
    uint64_t u_core_wkup_count_wr_data_o;  /* 64-bit */
    uint8_t u_core_wkup_intr_o;  /* 1-bit */
    uint8_t u_intr_hw_clk_i;  /* 1-bit */
    uint8_t u_intr_hw_event_intr_i;  /* 2-bit */
    uint8_t u_intr_hw_hw2reg_intr_state_d_o;  /* 2-bit */
    uint8_t u_intr_hw_hw2reg_intr_state_de_o;  /* 1-bit */
    uint8_t u_intr_hw_intr_o;  /* 2-bit */
    uint8_t u_intr_hw_reg2hw_intr_enable_q_i;  /* 2-bit */
    uint8_t u_intr_hw_reg2hw_intr_state_q_i;  /* 2-bit */
    uint8_t u_intr_hw_reg2hw_intr_test_q_i;  /* 2-bit */
    uint8_t u_intr_hw_reg2hw_intr_test_qe_i;  /* 1-bit */
    uint8_t u_intr_hw_rst_ni;  /* 1-bit */
    uint8_t u_intr_hw_status;  /* 2-bit */
    uint8_t u_intr_sync_clk_i;  /* 1-bit */
    uint8_t u_intr_sync_d_i;  /* 2-bit */
    uint8_t u_intr_sync_g_sync_u_sync_clk_i;  /* 1-bit */
    uint8_t u_intr_sync_g_sync_u_sync_d_i;  /* 2-bit */
    uint8_t u_intr_sync_g_sync_u_sync_d_o;  /* 2-bit */
    uint8_t u_intr_sync_g_sync_u_sync_q_o;  /* 2-bit */
    uint8_t u_intr_sync_g_sync_u_sync_rst_ni;  /* 1-bit */
    uint8_t u_intr_sync_g_sync_u_sync_u_sync_1_clk_i;  /* 1-bit */
    uint8_t u_intr_sync_g_sync_u_sync_u_sync_1_d_i;  /* 2-bit */
    uint8_t u_intr_sync_g_sync_u_sync_u_sync_1_q_o;  /* 2-bit */
    uint8_t u_intr_sync_g_sync_u_sync_u_sync_1_rst_ni;  /* 1-bit */
    uint8_t u_intr_sync_g_sync_u_sync_u_sync_2_clk_i;  /* 1-bit */
    uint8_t u_intr_sync_g_sync_u_sync_u_sync_2_d_i;  /* 2-bit */
    uint8_t u_intr_sync_g_sync_u_sync_u_sync_2_q_o;  /* 2-bit */
    uint8_t u_intr_sync_g_sync_u_sync_u_sync_2_rst_ni;  /* 1-bit */
    uint8_t u_intr_sync_q_negedge_pulse_o;  /* 2-bit */
    uint8_t u_intr_sync_q_posedge_pulse_o;  /* 2-bit */
    uint8_t u_intr_sync_q_sync_d;  /* 2-bit */
    uint8_t u_intr_sync_q_sync_o;  /* 2-bit */
    uint8_t u_intr_sync_q_sync_q;  /* 2-bit */
    uint8_t u_intr_sync_rst_ni;  /* 1-bit */
    uint8_t u_lc_sync_escalate_en_clk_i;  /* 1-bit */
    uint8_t u_lc_sync_escalate_en_lc_en_i;  /* 4-bit */
    uint8_t u_lc_sync_escalate_en_lc_en_o_0_;  /* 4-bit */
    uint8_t u_lc_sync_escalate_en_lc_en_o_1_;  /* 4-bit */
    uint8_t u_lc_sync_escalate_en_lc_en_o_2_;  /* 4-bit */
    uint8_t u_lc_sync_escalate_en_rst_ni;  /* 1-bit */
    uint16_t u_reg_addr_hit;  /* 14-bit */
    uint8_t u_reg_alert_test_flds_we;  /* 1-bit */
    uint8_t u_reg_alert_test_we;  /* 1-bit */
    uint32_t u_reg_aon_wdog_bark_thold_qs;  /* 32-bit */
    uint32_t u_reg_aon_wdog_bark_thold_qs_int;  /* 32-bit */
    uint32_t u_reg_aon_wdog_bite_thold_qs;  /* 32-bit */
    uint32_t u_reg_aon_wdog_bite_thold_qs_int;  /* 32-bit */
    uint32_t u_reg_aon_wdog_count_ds;  /* 32-bit */
    uint32_t u_reg_aon_wdog_count_ds_int;  /* 32-bit */
    uint32_t u_reg_aon_wdog_count_qs;  /* 32-bit */
    uint32_t u_reg_aon_wdog_count_qs_int;  /* 32-bit */
    uint8_t u_reg_aon_wdog_ctrl_enable_qs_int;  /* 1-bit */
    uint8_t u_reg_aon_wdog_ctrl_pause_in_sleep_qs_int;  /* 1-bit */
    uint8_t u_reg_aon_wdog_ctrl_qs;  /* 2-bit */
    uint8_t u_reg_aon_wkup_cause_ds;  /* 1-bit */
    uint8_t u_reg_aon_wkup_cause_ds_int;  /* 1-bit */
    uint8_t u_reg_aon_wkup_cause_qs;  /* 1-bit */
    uint8_t u_reg_aon_wkup_cause_qs_int;  /* 1-bit */
    uint32_t u_reg_aon_wkup_count_hi_ds;  /* 32-bit */
    uint32_t u_reg_aon_wkup_count_hi_ds_int;  /* 32-bit */
    uint32_t u_reg_aon_wkup_count_hi_qs;  /* 32-bit */
    uint32_t u_reg_aon_wkup_count_hi_qs_int;  /* 32-bit */
    uint32_t u_reg_aon_wkup_count_lo_ds;  /* 32-bit */
    uint32_t u_reg_aon_wkup_count_lo_ds_int;  /* 32-bit */
    uint32_t u_reg_aon_wkup_count_lo_qs;  /* 32-bit */
    uint32_t u_reg_aon_wkup_count_lo_qs_int;  /* 32-bit */
    uint8_t u_reg_aon_wkup_ctrl_enable_qs_int;  /* 1-bit */
    uint16_t u_reg_aon_wkup_ctrl_prescaler_qs_int;  /* 12-bit */
    uint16_t u_reg_aon_wkup_ctrl_qs;  /* 13-bit */
    uint32_t u_reg_aon_wkup_thold_hi_qs;  /* 32-bit */
    uint32_t u_reg_aon_wkup_thold_hi_qs_int;  /* 32-bit */
    uint32_t u_reg_aon_wkup_thold_lo_qs;  /* 32-bit */
    uint32_t u_reg_aon_wkup_thold_lo_qs_int;  /* 32-bit */
    uint8_t u_reg_clk_aon_i;  /* 1-bit */
    uint8_t u_reg_clk_i;  /* 1-bit */
    uint8_t u_reg_err_q;  /* 1-bit */
    uint8_t u_reg_hw2reg_intr_state_wdog_timer_bark_d;  /* 1-bit */
    uint8_t u_reg_hw2reg_intr_state_wdog_timer_bark_de;  /* 1-bit */
    uint8_t u_reg_hw2reg_intr_state_wkup_timer_expired_d;  /* 1-bit */
    uint8_t u_reg_hw2reg_intr_state_wkup_timer_expired_de;  /* 1-bit */
    uint32_t u_reg_hw2reg_wdog_count_d;  /* 32-bit */
    uint8_t u_reg_hw2reg_wdog_count_de;  /* 1-bit */
    uint8_t u_reg_hw2reg_wkup_cause_d;  /* 1-bit */
    uint8_t u_reg_hw2reg_wkup_cause_de;  /* 1-bit */
    uint32_t u_reg_hw2reg_wkup_count_hi_d;  /* 32-bit */
    uint8_t u_reg_hw2reg_wkup_count_hi_de;  /* 1-bit */
    uint32_t u_reg_hw2reg_wkup_count_lo_d;  /* 32-bit */
    uint8_t u_reg_hw2reg_wkup_count_lo_de;  /* 1-bit */
    uint8_t u_reg_intg_err;  /* 1-bit */
    uint8_t u_reg_intg_err_o;  /* 1-bit */
    uint8_t u_reg_intr_state_wdog_timer_bark_qs;  /* 1-bit */
    uint8_t u_reg_intr_state_we;  /* 1-bit */
    uint8_t u_reg_intr_state_wkup_timer_expired_qs;  /* 1-bit */
    uint8_t u_reg_intr_test_flds_we;  /* 2-bit */
    uint8_t u_reg_intr_test_we;  /* 1-bit */
    uint16_t u_reg_racl_addr_hit_read;  /* 14-bit */
    uint16_t u_reg_racl_addr_hit_write;  /* 14-bit */
    uint8_t u_reg_racl_error_o_ctn_uid;  /* 1-bit */
    uint8_t u_reg_racl_error_o_overflow;  /* 1-bit */
    uint8_t u_reg_racl_error_o_racl_role;  /* 1-bit */
    uint8_t u_reg_racl_error_o_read_access;  /* 1-bit */
    uint32_t u_reg_racl_error_o_request_address;  /* 32-bit */
    uint8_t u_reg_racl_error_o_valid;  /* 1-bit */
    uint8_t u_reg_racl_policies_i_0__read_perm;  /* 2-bit */
    uint8_t u_reg_racl_policies_i_0__write_perm;  /* 2-bit */
    uint8_t u_reg_racl_role_vec;  /* 2-bit */
    uint8_t u_reg_reg2hw_alert_test_q;  /* 1-bit */
    uint8_t u_reg_reg2hw_alert_test_qe;  /* 1-bit */
    uint8_t u_reg_reg2hw_intr_state_wdog_timer_bark_q;  /* 1-bit */
    uint8_t u_reg_reg2hw_intr_state_wkup_timer_expired_q;  /* 1-bit */
    uint8_t u_reg_reg2hw_intr_test_wdog_timer_bark_q;  /* 1-bit */
    uint8_t u_reg_reg2hw_intr_test_wdog_timer_bark_qe;  /* 1-bit */
    uint8_t u_reg_reg2hw_intr_test_wkup_timer_expired_q;  /* 1-bit */
    uint8_t u_reg_reg2hw_intr_test_wkup_timer_expired_qe;  /* 1-bit */
    uint32_t u_reg_reg2hw_wdog_bark_thold_q;  /* 32-bit */
    uint32_t u_reg_reg2hw_wdog_bite_thold_q;  /* 32-bit */
    uint32_t u_reg_reg2hw_wdog_count_q;  /* 32-bit */
    uint8_t u_reg_reg2hw_wdog_ctrl_enable_q;  /* 1-bit */
    uint8_t u_reg_reg2hw_wdog_ctrl_pause_in_sleep_q;  /* 1-bit */
    uint8_t u_reg_reg2hw_wkup_cause_q;  /* 1-bit */
    uint32_t u_reg_reg2hw_wkup_count_hi_q;  /* 32-bit */
    uint32_t u_reg_reg2hw_wkup_count_lo_q;  /* 32-bit */
    uint8_t u_reg_reg2hw_wkup_ctrl_enable_q;  /* 1-bit */
    uint16_t u_reg_reg2hw_wkup_ctrl_prescaler_q;  /* 12-bit */
    uint8_t u_reg_reg2hw_wkup_ctrl_prescaler_qe;  /* 1-bit */
    uint32_t u_reg_reg2hw_wkup_thold_hi_q;  /* 32-bit */
    uint32_t u_reg_reg2hw_wkup_thold_lo_q;  /* 32-bit */
    uint8_t u_reg_reg_addr;  /* 6-bit */
    uint8_t u_reg_reg_be;  /* 4-bit */
    uint8_t u_reg_reg_busy_sel;  /* 1-bit */
    uint32_t u_reg_reg_rdata_next;  /* 32-bit */
    uint8_t u_reg_reg_we;  /* 1-bit */
    uint16_t u_reg_reg_we_check;  /* 14-bit */
    uint8_t u_reg_reg_we_err;  /* 1-bit */
    uint8_t u_reg_rst_aon_ni;  /* 1-bit */
    uint8_t u_reg_rst_ni;  /* 1-bit */
    uint32_t u_reg_tl_i_a_address;  /* 32-bit */
    uint32_t u_reg_tl_i_a_data;  /* 32-bit */
    uint8_t u_reg_tl_i_a_mask;  /* 4-bit */
    uint8_t u_reg_tl_i_a_opcode;  /* 3-bit */
    uint8_t u_reg_tl_i_a_param;  /* 3-bit */
    uint8_t u_reg_tl_i_a_size;  /* 2-bit */
    uint8_t u_reg_tl_i_a_source;  /* 8-bit */
    uint8_t u_reg_tl_i_a_user_cmd_intg;  /* 7-bit */
    uint8_t u_reg_tl_i_a_user_data_intg;  /* 7-bit */
    uint8_t u_reg_tl_i_a_user_instr_type;  /* 4-bit */
    uint8_t u_reg_tl_i_a_user_rsvd;  /* 5-bit */
    uint8_t u_reg_tl_i_a_valid;  /* 1-bit */
    uint8_t u_reg_tl_i_d_ready;  /* 1-bit */
    uint8_t u_reg_tl_o_a_ready;  /* 1-bit */
    uint32_t u_reg_tl_o_d_data;  /* 32-bit */
    uint8_t u_reg_tl_o_d_error;  /* 1-bit */
    uint8_t u_reg_tl_o_d_opcode;  /* 3-bit */
    uint8_t u_reg_tl_o_d_param;  /* 3-bit */
    uint8_t u_reg_tl_o_d_sink;  /* 1-bit */
    uint8_t u_reg_tl_o_d_size;  /* 2-bit */
    uint8_t u_reg_tl_o_d_source;  /* 8-bit */
    uint8_t u_reg_tl_o_d_user_data_intg;  /* 7-bit */
    uint8_t u_reg_tl_o_d_user_rsp_intg;  /* 7-bit */
    uint8_t u_reg_tl_o_d_valid;  /* 1-bit */
    uint8_t u_reg_u_alert_test_d;  /* 1-bit */
    uint8_t u_reg_u_alert_test_ds;  /* 1-bit */
    uint8_t u_reg_u_alert_test_q;  /* 1-bit */
    uint8_t u_reg_u_alert_test_qe;  /* 1-bit */
    uint8_t u_reg_u_alert_test_qre;  /* 1-bit */
    uint8_t u_reg_u_alert_test_qs;  /* 1-bit */
    uint8_t u_reg_u_alert_test_re;  /* 1-bit */
    uint8_t u_reg_u_alert_test_wd;  /* 1-bit */
    uint8_t u_reg_u_alert_test_we;  /* 1-bit */
    uint8_t u_reg_u_chk_err_o;  /* 1-bit */
    uint32_t u_reg_u_chk_tl_i_a_address;  /* 32-bit */
    uint32_t u_reg_u_chk_tl_i_a_data;  /* 32-bit */
    uint8_t u_reg_u_chk_tl_i_a_mask;  /* 4-bit */
    uint8_t u_reg_u_chk_tl_i_a_opcode;  /* 3-bit */
    uint8_t u_reg_u_chk_tl_i_a_param;  /* 3-bit */
    uint8_t u_reg_u_chk_tl_i_a_size;  /* 2-bit */
    uint8_t u_reg_u_chk_tl_i_a_source;  /* 8-bit */
    uint8_t u_reg_u_chk_tl_i_a_user_cmd_intg;  /* 7-bit */
    uint8_t u_reg_u_chk_tl_i_a_user_data_intg;  /* 7-bit */
    uint8_t u_reg_u_chk_tl_i_a_user_instr_type;  /* 4-bit */
    uint8_t u_reg_u_chk_tl_i_a_user_rsvd;  /* 5-bit */
    uint8_t u_reg_u_chk_tl_i_a_valid;  /* 1-bit */
    uint8_t u_reg_u_chk_tl_i_d_ready;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wdog_timer_bark_clk_i;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wdog_timer_bark_d;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wdog_timer_bark_de;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wdog_timer_bark_ds;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wdog_timer_bark_q;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wdog_timer_bark_qe;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wdog_timer_bark_qs;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wdog_timer_bark_rst_ni;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wdog_timer_bark_wd;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wdog_timer_bark_we;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wdog_timer_bark_wr_data;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wdog_timer_bark_wr_en;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wdog_timer_bark_wr_en_data_arb_d;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wdog_timer_bark_wr_en_data_arb_de;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wdog_timer_bark_wr_en_data_arb_q;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wdog_timer_bark_wr_en_data_arb_wd;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wdog_timer_bark_wr_en_data_arb_we;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wdog_timer_bark_wr_en_data_arb_wr_data;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wdog_timer_bark_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wkup_timer_expired_clk_i;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wkup_timer_expired_d;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wkup_timer_expired_de;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wkup_timer_expired_ds;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wkup_timer_expired_q;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wkup_timer_expired_qe;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wkup_timer_expired_qs;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wkup_timer_expired_rst_ni;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wkup_timer_expired_wd;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wkup_timer_expired_we;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wkup_timer_expired_wr_data;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wkup_timer_expired_wr_en;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wkup_timer_expired_wr_en_data_arb_d;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wkup_timer_expired_wr_en_data_arb_de;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wkup_timer_expired_wr_en_data_arb_q;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wkup_timer_expired_wr_en_data_arb_wd;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wkup_timer_expired_wr_en_data_arb_we;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wkup_timer_expired_wr_en_data_arb_wr_data;  /* 1-bit */
    uint8_t u_reg_u_intr_state_wkup_timer_expired_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_intr_test_wdog_timer_bark_d;  /* 1-bit */
    uint8_t u_reg_u_intr_test_wdog_timer_bark_ds;  /* 1-bit */
    uint8_t u_reg_u_intr_test_wdog_timer_bark_q;  /* 1-bit */
    uint8_t u_reg_u_intr_test_wdog_timer_bark_qe;  /* 1-bit */
    uint8_t u_reg_u_intr_test_wdog_timer_bark_qre;  /* 1-bit */
    uint8_t u_reg_u_intr_test_wdog_timer_bark_qs;  /* 1-bit */
    uint8_t u_reg_u_intr_test_wdog_timer_bark_re;  /* 1-bit */
    uint8_t u_reg_u_intr_test_wdog_timer_bark_wd;  /* 1-bit */
    uint8_t u_reg_u_intr_test_wdog_timer_bark_we;  /* 1-bit */
    uint8_t u_reg_u_intr_test_wkup_timer_expired_d;  /* 1-bit */
    uint8_t u_reg_u_intr_test_wkup_timer_expired_ds;  /* 1-bit */
    uint8_t u_reg_u_intr_test_wkup_timer_expired_q;  /* 1-bit */
    uint8_t u_reg_u_intr_test_wkup_timer_expired_qe;  /* 1-bit */
    uint8_t u_reg_u_intr_test_wkup_timer_expired_qre;  /* 1-bit */
    uint8_t u_reg_u_intr_test_wkup_timer_expired_qs;  /* 1-bit */
    uint8_t u_reg_u_intr_test_wkup_timer_expired_re;  /* 1-bit */
    uint8_t u_reg_u_intr_test_wkup_timer_expired_wd;  /* 1-bit */
    uint8_t u_reg_u_intr_test_wkup_timer_expired_we;  /* 1-bit */
    uint8_t u_reg_u_prim_reg_we_check_clk_i;  /* 1-bit */
    uint8_t u_reg_u_prim_reg_we_check_en_i;  /* 1-bit */
    uint8_t u_reg_u_prim_reg_we_check_err_o;  /* 1-bit */
    uint16_t u_reg_u_prim_reg_we_check_oh_i;  /* 14-bit */
    uint8_t u_reg_u_prim_reg_we_check_rst_ni;  /* 1-bit */
    uint8_t u_reg_u_reg_if_a_ack;  /* 1-bit */
    uint8_t u_reg_u_reg_if_addr_align_err;  /* 1-bit */
    uint8_t u_reg_u_reg_if_addr_o;  /* 6-bit */
    uint8_t u_reg_u_reg_if_be_o;  /* 4-bit */
    uint8_t u_reg_u_reg_if_busy_i;  /* 1-bit */
    uint8_t u_reg_u_reg_if_clk_i;  /* 1-bit */
    uint8_t u_reg_u_reg_if_d_ack;  /* 1-bit */
    uint8_t u_reg_u_reg_if_en_ifetch_i;  /* 4-bit */
    uint8_t u_reg_u_reg_if_err_internal;  /* 1-bit */
    uint8_t u_reg_u_reg_if_error_i;  /* 1-bit */
    uint8_t u_reg_u_reg_if_error_q;  /* 1-bit */
    uint8_t u_reg_u_reg_if_intg_error_o;  /* 1-bit */
    uint8_t u_reg_u_reg_if_outstanding_q;  /* 1-bit */
    uint8_t u_reg_u_reg_if_rd_req;  /* 1-bit */
    uint32_t u_reg_u_reg_if_rdata_i;  /* 32-bit */
    uint32_t u_reg_u_reg_if_rdata_q;  /* 32-bit */
    uint8_t u_reg_u_reg_if_re_o;  /* 1-bit */
    uint8_t u_reg_u_reg_if_reqid_q;  /* 8-bit */
    uint8_t u_reg_u_reg_if_reqsz_q;  /* 2-bit */
    uint8_t u_reg_u_reg_if_rspop_q;  /* 3-bit */
    uint8_t u_reg_u_reg_if_rst_ni;  /* 1-bit */
    uint32_t u_reg_u_reg_if_tl_i_a_address;  /* 32-bit */
    uint32_t u_reg_u_reg_if_tl_i_a_data;  /* 32-bit */
    uint8_t u_reg_u_reg_if_tl_i_a_mask;  /* 4-bit */
    uint8_t u_reg_u_reg_if_tl_i_a_opcode;  /* 3-bit */
    uint8_t u_reg_u_reg_if_tl_i_a_param;  /* 3-bit */
    uint8_t u_reg_u_reg_if_tl_i_a_size;  /* 2-bit */
    uint8_t u_reg_u_reg_if_tl_i_a_source;  /* 8-bit */
    uint8_t u_reg_u_reg_if_tl_i_a_user_cmd_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_tl_i_a_user_data_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_tl_i_a_user_instr_type;  /* 4-bit */
    uint8_t u_reg_u_reg_if_tl_i_a_user_rsvd;  /* 5-bit */
    uint8_t u_reg_u_reg_if_tl_i_a_valid;  /* 1-bit */
    uint8_t u_reg_u_reg_if_tl_i_d_ready;  /* 1-bit */
    uint8_t u_reg_u_reg_if_tl_o_a_ready;  /* 1-bit */
    uint32_t u_reg_u_reg_if_tl_o_d_data;  /* 32-bit */
    uint8_t u_reg_u_reg_if_tl_o_d_error;  /* 1-bit */
    uint8_t u_reg_u_reg_if_tl_o_d_opcode;  /* 3-bit */
    uint8_t u_reg_u_reg_if_tl_o_d_param;  /* 3-bit */
    uint8_t u_reg_u_reg_if_tl_o_d_sink;  /* 1-bit */
    uint8_t u_reg_u_reg_if_tl_o_d_size;  /* 2-bit */
    uint8_t u_reg_u_reg_if_tl_o_d_source;  /* 8-bit */
    uint8_t u_reg_u_reg_if_tl_o_d_user_data_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_tl_o_d_user_rsp_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_tl_o_d_valid;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_err_addr_sz_chk;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_err_clk_i;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_err_err_o;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_err_fulldata_chk;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_err_mask;  /* 4-bit */
    uint8_t u_reg_u_reg_if_u_err_mask_chk;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_err_rst_ni;  /* 1-bit */
    uint32_t u_reg_u_reg_if_u_err_tl_i_a_address;  /* 32-bit */
    uint32_t u_reg_u_reg_if_u_err_tl_i_a_data;  /* 32-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_a_mask;  /* 4-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_a_opcode;  /* 3-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_a_param;  /* 3-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_a_size;  /* 2-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_a_source;  /* 8-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_a_user_cmd_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_a_user_data_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_a_user_instr_type;  /* 4-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_a_user_rsvd;  /* 5-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_a_valid;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_d_ready;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_data_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_rsp_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_a_ready;  /* 1-bit */
    uint32_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_d_data;  /* 32-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_d_error;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_d_opcode;  /* 3-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_d_param;  /* 3-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_d_sink;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_d_size;  /* 2-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_d_source;  /* 8-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_d_user_data_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_d_user_rsp_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_d_valid;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_a_ready;  /* 1-bit */
    uint32_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_d_data;  /* 32-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_d_error;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_d_opcode;  /* 3-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_d_param;  /* 3-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_d_sink;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_d_size;  /* 2-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_d_source;  /* 8-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_d_user_data_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_d_user_rsp_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_d_valid;  /* 1-bit */
    uint32_t u_reg_u_reg_if_wdata_o;  /* 32-bit */
    uint8_t u_reg_u_reg_if_we_o;  /* 1-bit */
    uint8_t u_reg_u_reg_if_wr_req;  /* 1-bit */
    uint8_t u_reg_u_rsp_intg_gen_data_intg;  /* 7-bit */
    uint32_t u_reg_u_rsp_intg_gen_gen_data_intg_u_tlul_data_integ_enc_data_i;  /* 32-bit */
    uint64_t u_reg_u_rsp_intg_gen_gen_data_intg_u_tlul_data_integ_enc_data_intg_o;  /* 39-bit */
    uint32_t u_reg_u_rsp_intg_gen_gen_data_intg_u_tlul_data_integ_enc_u_data_gen_data_i;  /* 32-bit */
    uint64_t u_reg_u_rsp_intg_gen_gen_data_intg_u_tlul_data_integ_enc_u_data_gen_data_o;  /* 39-bit */
    uint64_t u_reg_u_rsp_intg_gen_gen_rsp_intg_u_rsp_gen_data_i;  /* 57-bit */
    uint64_t u_reg_u_rsp_intg_gen_gen_rsp_intg_u_rsp_gen_data_o;  /* 64-bit */
    uint8_t u_reg_u_rsp_intg_gen_qpinl5_payload_error;  /* 1-bit */
    uint8_t u_reg_u_rsp_intg_gen_qpinl5_payload_opcode;  /* 3-bit */
    uint8_t u_reg_u_rsp_intg_gen_qpinl5_payload_size;  /* 2-bit */
    uint8_t u_reg_u_rsp_intg_gen_rsp_intg;  /* 7-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_i_a_ready;  /* 1-bit */
    uint32_t u_reg_u_rsp_intg_gen_tl_i_d_data;  /* 32-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_i_d_error;  /* 1-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_i_d_opcode;  /* 3-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_i_d_param;  /* 3-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_i_d_sink;  /* 1-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_i_d_size;  /* 2-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_i_d_source;  /* 8-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_i_d_user_data_intg;  /* 7-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_i_d_user_rsp_intg;  /* 7-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_i_d_valid;  /* 1-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_o_a_ready;  /* 1-bit */
    uint32_t u_reg_u_rsp_intg_gen_tl_o_d_data;  /* 32-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_o_d_error;  /* 1-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_o_d_opcode;  /* 3-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_o_d_param;  /* 3-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_o_d_sink;  /* 1-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_o_d_size;  /* 2-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_o_d_source;  /* 8-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_o_d_user_data_intg;  /* 7-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_o_d_user_rsp_intg;  /* 7-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_o_d_valid;  /* 1-bit */
    uint8_t u_reg_u_wdog_bark_thold_cdc_clk_dst_i;  /* 1-bit */
    uint8_t u_reg_u_wdog_bark_thold_cdc_clk_src_i;  /* 1-bit */
    uint32_t u_reg_u_wdog_bark_thold_cdc_dst_ds_i;  /* 32-bit */
    uint32_t u_reg_u_wdog_bark_thold_cdc_dst_qs_i;  /* 32-bit */
    uint8_t u_reg_u_wdog_bark_thold_cdc_dst_re_o;  /* 1-bit */
    uint8_t u_reg_u_wdog_bark_thold_cdc_dst_regwen_o;  /* 1-bit */
    uint8_t u_reg_u_wdog_bark_thold_cdc_dst_update_i;  /* 1-bit */
    uint32_t u_reg_u_wdog_bark_thold_cdc_dst_wd_o;  /* 32-bit */
    uint8_t u_reg_u_wdog_bark_thold_cdc_dst_we_o;  /* 1-bit */
    uint8_t u_reg_u_wdog_bark_thold_cdc_rst_dst_ni;  /* 1-bit */
    uint8_t u_reg_u_wdog_bark_thold_cdc_rst_src_ni;  /* 1-bit */
    uint8_t u_reg_u_wdog_bark_thold_cdc_src_busy_o;  /* 1-bit */
    uint32_t u_reg_u_wdog_bark_thold_cdc_src_qs_o;  /* 32-bit */
    uint8_t u_reg_u_wdog_bark_thold_cdc_src_re_i;  /* 1-bit */
    uint8_t u_reg_u_wdog_bark_thold_cdc_src_regwen_i;  /* 1-bit */
    uint32_t u_reg_u_wdog_bark_thold_cdc_src_wd_i;  /* 32-bit */
    uint8_t u_reg_u_wdog_bark_thold_cdc_src_we_i;  /* 1-bit */
    uint8_t u_reg_u_wdog_bark_thold_clk_i;  /* 1-bit */
    uint32_t u_reg_u_wdog_bark_thold_d;  /* 32-bit */
    uint8_t u_reg_u_wdog_bark_thold_de;  /* 1-bit */
    uint32_t u_reg_u_wdog_bark_thold_ds;  /* 32-bit */
    uint32_t u_reg_u_wdog_bark_thold_q;  /* 32-bit */
    uint8_t u_reg_u_wdog_bark_thold_qe;  /* 1-bit */
    uint32_t u_reg_u_wdog_bark_thold_qs;  /* 32-bit */
    uint8_t u_reg_u_wdog_bark_thold_rst_ni;  /* 1-bit */
    uint32_t u_reg_u_wdog_bark_thold_wd;  /* 32-bit */
    uint8_t u_reg_u_wdog_bark_thold_we;  /* 1-bit */
    uint32_t u_reg_u_wdog_bark_thold_wr_data;  /* 32-bit */
    uint8_t u_reg_u_wdog_bark_thold_wr_en;  /* 1-bit */
    uint32_t u_reg_u_wdog_bark_thold_wr_en_data_arb_d;  /* 32-bit */
    uint8_t u_reg_u_wdog_bark_thold_wr_en_data_arb_de;  /* 1-bit */
    uint32_t u_reg_u_wdog_bark_thold_wr_en_data_arb_q;  /* 32-bit */
    uint32_t u_reg_u_wdog_bark_thold_wr_en_data_arb_wd;  /* 32-bit */
    uint8_t u_reg_u_wdog_bark_thold_wr_en_data_arb_we;  /* 1-bit */
    uint32_t u_reg_u_wdog_bark_thold_wr_en_data_arb_wr_data;  /* 32-bit */
    uint8_t u_reg_u_wdog_bark_thold_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_wdog_bite_thold_cdc_clk_dst_i;  /* 1-bit */
    uint8_t u_reg_u_wdog_bite_thold_cdc_clk_src_i;  /* 1-bit */
    uint32_t u_reg_u_wdog_bite_thold_cdc_dst_ds_i;  /* 32-bit */
    uint32_t u_reg_u_wdog_bite_thold_cdc_dst_qs_i;  /* 32-bit */
    uint8_t u_reg_u_wdog_bite_thold_cdc_dst_re_o;  /* 1-bit */
    uint8_t u_reg_u_wdog_bite_thold_cdc_dst_regwen_o;  /* 1-bit */
    uint8_t u_reg_u_wdog_bite_thold_cdc_dst_update_i;  /* 1-bit */
    uint32_t u_reg_u_wdog_bite_thold_cdc_dst_wd_o;  /* 32-bit */
    uint8_t u_reg_u_wdog_bite_thold_cdc_dst_we_o;  /* 1-bit */
    uint8_t u_reg_u_wdog_bite_thold_cdc_rst_dst_ni;  /* 1-bit */
    uint8_t u_reg_u_wdog_bite_thold_cdc_rst_src_ni;  /* 1-bit */
    uint8_t u_reg_u_wdog_bite_thold_cdc_src_busy_o;  /* 1-bit */
    uint32_t u_reg_u_wdog_bite_thold_cdc_src_qs_o;  /* 32-bit */
    uint8_t u_reg_u_wdog_bite_thold_cdc_src_re_i;  /* 1-bit */
    uint8_t u_reg_u_wdog_bite_thold_cdc_src_regwen_i;  /* 1-bit */
    uint32_t u_reg_u_wdog_bite_thold_cdc_src_wd_i;  /* 32-bit */
    uint8_t u_reg_u_wdog_bite_thold_cdc_src_we_i;  /* 1-bit */
    uint8_t u_reg_u_wdog_bite_thold_clk_i;  /* 1-bit */
    uint32_t u_reg_u_wdog_bite_thold_d;  /* 32-bit */
    uint8_t u_reg_u_wdog_bite_thold_de;  /* 1-bit */
    uint32_t u_reg_u_wdog_bite_thold_ds;  /* 32-bit */
    uint32_t u_reg_u_wdog_bite_thold_q;  /* 32-bit */
    uint8_t u_reg_u_wdog_bite_thold_qe;  /* 1-bit */
    uint32_t u_reg_u_wdog_bite_thold_qs;  /* 32-bit */
    uint8_t u_reg_u_wdog_bite_thold_rst_ni;  /* 1-bit */
    uint32_t u_reg_u_wdog_bite_thold_wd;  /* 32-bit */
    uint8_t u_reg_u_wdog_bite_thold_we;  /* 1-bit */
    uint32_t u_reg_u_wdog_bite_thold_wr_data;  /* 32-bit */
    uint8_t u_reg_u_wdog_bite_thold_wr_en;  /* 1-bit */
    uint32_t u_reg_u_wdog_bite_thold_wr_en_data_arb_d;  /* 32-bit */
    uint8_t u_reg_u_wdog_bite_thold_wr_en_data_arb_de;  /* 1-bit */
    uint32_t u_reg_u_wdog_bite_thold_wr_en_data_arb_q;  /* 32-bit */
    uint32_t u_reg_u_wdog_bite_thold_wr_en_data_arb_wd;  /* 32-bit */
    uint8_t u_reg_u_wdog_bite_thold_wr_en_data_arb_we;  /* 1-bit */
    uint32_t u_reg_u_wdog_bite_thold_wr_en_data_arb_wr_data;  /* 32-bit */
    uint8_t u_reg_u_wdog_bite_thold_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_wdog_count_cdc_clk_dst_i;  /* 1-bit */
    uint8_t u_reg_u_wdog_count_cdc_clk_src_i;  /* 1-bit */
    uint32_t u_reg_u_wdog_count_cdc_dst_ds_i;  /* 32-bit */
    uint32_t u_reg_u_wdog_count_cdc_dst_qs_i;  /* 32-bit */
    uint8_t u_reg_u_wdog_count_cdc_dst_re_o;  /* 1-bit */
    uint8_t u_reg_u_wdog_count_cdc_dst_regwen_o;  /* 1-bit */
    uint8_t u_reg_u_wdog_count_cdc_dst_update_i;  /* 1-bit */
    uint32_t u_reg_u_wdog_count_cdc_dst_wd_o;  /* 32-bit */
    uint8_t u_reg_u_wdog_count_cdc_dst_we_o;  /* 1-bit */
    uint8_t u_reg_u_wdog_count_cdc_rst_dst_ni;  /* 1-bit */
    uint8_t u_reg_u_wdog_count_cdc_rst_src_ni;  /* 1-bit */
    uint8_t u_reg_u_wdog_count_cdc_src_busy_o;  /* 1-bit */
    uint32_t u_reg_u_wdog_count_cdc_src_qs_o;  /* 32-bit */
    uint8_t u_reg_u_wdog_count_cdc_src_re_i;  /* 1-bit */
    uint8_t u_reg_u_wdog_count_cdc_src_regwen_i;  /* 1-bit */
    uint32_t u_reg_u_wdog_count_cdc_src_wd_i;  /* 32-bit */
    uint8_t u_reg_u_wdog_count_cdc_src_we_i;  /* 1-bit */
    uint8_t u_reg_u_wdog_count_clk_i;  /* 1-bit */
    uint32_t u_reg_u_wdog_count_d;  /* 32-bit */
    uint8_t u_reg_u_wdog_count_de;  /* 1-bit */
    uint32_t u_reg_u_wdog_count_ds;  /* 32-bit */
    uint32_t u_reg_u_wdog_count_q;  /* 32-bit */
    uint8_t u_reg_u_wdog_count_qe;  /* 1-bit */
    uint32_t u_reg_u_wdog_count_qs;  /* 32-bit */
    uint8_t u_reg_u_wdog_count_rst_ni;  /* 1-bit */
    uint32_t u_reg_u_wdog_count_wd;  /* 32-bit */
    uint8_t u_reg_u_wdog_count_we;  /* 1-bit */
    uint32_t u_reg_u_wdog_count_wr_data;  /* 32-bit */
    uint8_t u_reg_u_wdog_count_wr_en;  /* 1-bit */
    uint32_t u_reg_u_wdog_count_wr_en_data_arb_d;  /* 32-bit */
    uint8_t u_reg_u_wdog_count_wr_en_data_arb_de;  /* 1-bit */
    uint32_t u_reg_u_wdog_count_wr_en_data_arb_q;  /* 32-bit */
    uint32_t u_reg_u_wdog_count_wr_en_data_arb_wd;  /* 32-bit */
    uint8_t u_reg_u_wdog_count_wr_en_data_arb_we;  /* 1-bit */
    uint32_t u_reg_u_wdog_count_wr_en_data_arb_wr_data;  /* 32-bit */
    uint8_t u_reg_u_wdog_count_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_cdc_clk_dst_i;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_cdc_clk_src_i;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_cdc_dst_ds_i;  /* 2-bit */
    uint8_t u_reg_u_wdog_ctrl_cdc_dst_qs_i;  /* 2-bit */
    uint8_t u_reg_u_wdog_ctrl_cdc_dst_re_o;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_cdc_dst_regwen_o;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_cdc_dst_update_i;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_cdc_dst_wd_o;  /* 2-bit */
    uint8_t u_reg_u_wdog_ctrl_cdc_dst_we_o;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_cdc_rst_dst_ni;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_cdc_rst_src_ni;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_cdc_src_busy_o;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_cdc_src_qs_o;  /* 2-bit */
    uint8_t u_reg_u_wdog_ctrl_cdc_src_re_i;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_cdc_src_regwen_i;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_cdc_src_wd_i;  /* 2-bit */
    uint8_t u_reg_u_wdog_ctrl_cdc_src_we_i;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_enable_clk_i;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_enable_d;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_enable_de;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_enable_ds;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_enable_q;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_enable_qe;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_enable_qs;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_enable_rst_ni;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_enable_wd;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_enable_we;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_enable_wr_data;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_enable_wr_en;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_enable_wr_en_data_arb_d;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_enable_wr_en_data_arb_de;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_enable_wr_en_data_arb_q;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_enable_wr_en_data_arb_wd;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_enable_wr_en_data_arb_we;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_enable_wr_en_data_arb_wr_data;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_enable_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_pause_in_sleep_clk_i;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_pause_in_sleep_d;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_pause_in_sleep_de;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_pause_in_sleep_ds;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_pause_in_sleep_q;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_pause_in_sleep_qe;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_pause_in_sleep_qs;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_pause_in_sleep_rst_ni;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_pause_in_sleep_wd;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_pause_in_sleep_we;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_pause_in_sleep_wr_data;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_pause_in_sleep_wr_en;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_pause_in_sleep_wr_en_data_arb_d;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_pause_in_sleep_wr_en_data_arb_de;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_pause_in_sleep_wr_en_data_arb_q;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_pause_in_sleep_wr_en_data_arb_wd;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_pause_in_sleep_wr_en_data_arb_we;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_pause_in_sleep_wr_en_data_arb_wr_data;  /* 1-bit */
    uint8_t u_reg_u_wdog_ctrl_pause_in_sleep_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_wdog_regwen_clk_i;  /* 1-bit */
    uint8_t u_reg_u_wdog_regwen_d;  /* 1-bit */
    uint8_t u_reg_u_wdog_regwen_de;  /* 1-bit */
    uint8_t u_reg_u_wdog_regwen_ds;  /* 1-bit */
    uint8_t u_reg_u_wdog_regwen_q;  /* 1-bit */
    uint8_t u_reg_u_wdog_regwen_qe;  /* 1-bit */
    uint8_t u_reg_u_wdog_regwen_qs;  /* 1-bit */
    uint8_t u_reg_u_wdog_regwen_rst_ni;  /* 1-bit */
    uint8_t u_reg_u_wdog_regwen_wd;  /* 1-bit */
    uint8_t u_reg_u_wdog_regwen_we;  /* 1-bit */
    uint8_t u_reg_u_wdog_regwen_wr_data;  /* 1-bit */
    uint8_t u_reg_u_wdog_regwen_wr_en;  /* 1-bit */
    uint8_t u_reg_u_wdog_regwen_wr_en_data_arb_d;  /* 1-bit */
    uint8_t u_reg_u_wdog_regwen_wr_en_data_arb_de;  /* 1-bit */
    uint8_t u_reg_u_wdog_regwen_wr_en_data_arb_q;  /* 1-bit */
    uint8_t u_reg_u_wdog_regwen_wr_en_data_arb_wd;  /* 1-bit */
    uint8_t u_reg_u_wdog_regwen_wr_en_data_arb_we;  /* 1-bit */
    uint8_t u_reg_u_wdog_regwen_wr_en_data_arb_wr_data;  /* 1-bit */
    uint8_t u_reg_u_wdog_regwen_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_cdc_clk_dst_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_cdc_clk_src_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_cdc_dst_ds_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_cdc_dst_qs_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_cdc_dst_re_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_cdc_dst_regwen_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_cdc_dst_update_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_cdc_dst_wd_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_cdc_dst_we_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_cdc_rst_dst_ni;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_cdc_rst_src_ni;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_cdc_src_busy_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_cdc_src_qs_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_cdc_src_re_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_cdc_src_regwen_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_cdc_src_wd_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_cdc_src_we_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_clk_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_d;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_de;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_ds;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_q;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_qe;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_qs;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_rst_ni;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_wd;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_we;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_wr_data;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_wr_en;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_wr_en_data_arb_d;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_wr_en_data_arb_de;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_wr_en_data_arb_q;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_wr_en_data_arb_wd;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_wr_en_data_arb_we;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_wr_en_data_arb_wr_data;  /* 1-bit */
    uint8_t u_reg_u_wkup_cause_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_wkup_count_hi_cdc_clk_dst_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_count_hi_cdc_clk_src_i;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_hi_cdc_dst_ds_i;  /* 32-bit */
    uint32_t u_reg_u_wkup_count_hi_cdc_dst_qs_i;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_hi_cdc_dst_re_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_count_hi_cdc_dst_regwen_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_count_hi_cdc_dst_update_i;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_hi_cdc_dst_wd_o;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_hi_cdc_dst_we_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_count_hi_cdc_rst_dst_ni;  /* 1-bit */
    uint8_t u_reg_u_wkup_count_hi_cdc_rst_src_ni;  /* 1-bit */
    uint8_t u_reg_u_wkup_count_hi_cdc_src_busy_o;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_hi_cdc_src_qs_o;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_hi_cdc_src_re_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_count_hi_cdc_src_regwen_i;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_hi_cdc_src_wd_i;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_hi_cdc_src_we_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_count_hi_clk_i;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_hi_d;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_hi_de;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_hi_ds;  /* 32-bit */
    uint32_t u_reg_u_wkup_count_hi_q;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_hi_qe;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_hi_qs;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_hi_rst_ni;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_hi_wd;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_hi_we;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_hi_wr_data;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_hi_wr_en;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_hi_wr_en_data_arb_d;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_hi_wr_en_data_arb_de;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_hi_wr_en_data_arb_q;  /* 32-bit */
    uint32_t u_reg_u_wkup_count_hi_wr_en_data_arb_wd;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_hi_wr_en_data_arb_we;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_hi_wr_en_data_arb_wr_data;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_hi_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_wkup_count_lo_cdc_clk_dst_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_count_lo_cdc_clk_src_i;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_lo_cdc_dst_ds_i;  /* 32-bit */
    uint32_t u_reg_u_wkup_count_lo_cdc_dst_qs_i;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_lo_cdc_dst_re_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_count_lo_cdc_dst_regwen_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_count_lo_cdc_dst_update_i;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_lo_cdc_dst_wd_o;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_lo_cdc_dst_we_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_count_lo_cdc_rst_dst_ni;  /* 1-bit */
    uint8_t u_reg_u_wkup_count_lo_cdc_rst_src_ni;  /* 1-bit */
    uint8_t u_reg_u_wkup_count_lo_cdc_src_busy_o;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_lo_cdc_src_qs_o;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_lo_cdc_src_re_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_count_lo_cdc_src_regwen_i;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_lo_cdc_src_wd_i;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_lo_cdc_src_we_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_count_lo_clk_i;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_lo_d;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_lo_de;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_lo_ds;  /* 32-bit */
    uint32_t u_reg_u_wkup_count_lo_q;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_lo_qe;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_lo_qs;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_lo_rst_ni;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_lo_wd;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_lo_we;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_lo_wr_data;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_lo_wr_en;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_lo_wr_en_data_arb_d;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_lo_wr_en_data_arb_de;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_lo_wr_en_data_arb_q;  /* 32-bit */
    uint32_t u_reg_u_wkup_count_lo_wr_en_data_arb_wd;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_lo_wr_en_data_arb_we;  /* 1-bit */
    uint32_t u_reg_u_wkup_count_lo_wr_en_data_arb_wr_data;  /* 32-bit */
    uint8_t u_reg_u_wkup_count_lo_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl0_qe_clk_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl0_qe_d_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl0_qe_q_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl0_qe_rst_ni;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_cdc_clk_dst_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_cdc_clk_src_i;  /* 1-bit */
    uint16_t u_reg_u_wkup_ctrl_cdc_dst_ds_i;  /* 13-bit */
    uint16_t u_reg_u_wkup_ctrl_cdc_dst_qs_i;  /* 13-bit */
    uint8_t u_reg_u_wkup_ctrl_cdc_dst_re_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_cdc_dst_regwen_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_cdc_dst_update_i;  /* 1-bit */
    uint16_t u_reg_u_wkup_ctrl_cdc_dst_wd_o;  /* 13-bit */
    uint8_t u_reg_u_wkup_ctrl_cdc_dst_we_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_cdc_rst_dst_ni;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_cdc_rst_src_ni;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_cdc_src_busy_o;  /* 1-bit */
    uint16_t u_reg_u_wkup_ctrl_cdc_src_qs_o;  /* 13-bit */
    uint8_t u_reg_u_wkup_ctrl_cdc_src_re_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_cdc_src_regwen_i;  /* 1-bit */
    uint16_t u_reg_u_wkup_ctrl_cdc_src_wd_i;  /* 13-bit */
    uint8_t u_reg_u_wkup_ctrl_cdc_src_we_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_enable_clk_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_enable_d;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_enable_de;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_enable_ds;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_enable_q;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_enable_qe;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_enable_qs;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_enable_rst_ni;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_enable_wd;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_enable_we;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_enable_wr_data;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_enable_wr_en;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_enable_wr_en_data_arb_d;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_enable_wr_en_data_arb_de;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_enable_wr_en_data_arb_q;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_enable_wr_en_data_arb_wd;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_enable_wr_en_data_arb_we;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_enable_wr_en_data_arb_wr_data;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_enable_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_wkup_ctrl_prescaler_clk_i;  /* 1-bit */
    uint16_t u_reg_u_wkup_ctrl_prescaler_d;  /* 12-bit */
    uint8_t u_reg_u_wkup_ctrl_prescaler_de;  /* 1-bit */
    uint16_t u_reg_u_wkup_ctrl_prescaler_ds;  /* 12-bit */
    uint16_t u_reg_u_wkup_ctrl_prescaler_q;  /* 12-bit */
    uint8_t u_reg_u_wkup_ctrl_prescaler_qe;  /* 1-bit */
    uint16_t u_reg_u_wkup_ctrl_prescaler_qs;  /* 12-bit */
    uint8_t u_reg_u_wkup_ctrl_prescaler_rst_ni;  /* 1-bit */
    uint16_t u_reg_u_wkup_ctrl_prescaler_wd;  /* 12-bit */
    uint8_t u_reg_u_wkup_ctrl_prescaler_we;  /* 1-bit */
    uint16_t u_reg_u_wkup_ctrl_prescaler_wr_data;  /* 12-bit */
    uint8_t u_reg_u_wkup_ctrl_prescaler_wr_en;  /* 1-bit */
    uint16_t u_reg_u_wkup_ctrl_prescaler_wr_en_data_arb_d;  /* 12-bit */
    uint8_t u_reg_u_wkup_ctrl_prescaler_wr_en_data_arb_de;  /* 1-bit */
    uint16_t u_reg_u_wkup_ctrl_prescaler_wr_en_data_arb_q;  /* 12-bit */
    uint16_t u_reg_u_wkup_ctrl_prescaler_wr_en_data_arb_wd;  /* 12-bit */
    uint8_t u_reg_u_wkup_ctrl_prescaler_wr_en_data_arb_we;  /* 1-bit */
    uint16_t u_reg_u_wkup_ctrl_prescaler_wr_en_data_arb_wr_data;  /* 12-bit */
    uint8_t u_reg_u_wkup_ctrl_prescaler_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_wkup_thold_hi_cdc_clk_dst_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_thold_hi_cdc_clk_src_i;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_hi_cdc_dst_ds_i;  /* 32-bit */
    uint32_t u_reg_u_wkup_thold_hi_cdc_dst_qs_i;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_hi_cdc_dst_re_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_thold_hi_cdc_dst_regwen_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_thold_hi_cdc_dst_update_i;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_hi_cdc_dst_wd_o;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_hi_cdc_dst_we_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_thold_hi_cdc_rst_dst_ni;  /* 1-bit */
    uint8_t u_reg_u_wkup_thold_hi_cdc_rst_src_ni;  /* 1-bit */
    uint8_t u_reg_u_wkup_thold_hi_cdc_src_busy_o;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_hi_cdc_src_qs_o;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_hi_cdc_src_re_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_thold_hi_cdc_src_regwen_i;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_hi_cdc_src_wd_i;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_hi_cdc_src_we_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_thold_hi_clk_i;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_hi_d;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_hi_de;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_hi_ds;  /* 32-bit */
    uint32_t u_reg_u_wkup_thold_hi_q;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_hi_qe;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_hi_qs;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_hi_rst_ni;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_hi_wd;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_hi_we;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_hi_wr_data;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_hi_wr_en;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_hi_wr_en_data_arb_d;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_hi_wr_en_data_arb_de;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_hi_wr_en_data_arb_q;  /* 32-bit */
    uint32_t u_reg_u_wkup_thold_hi_wr_en_data_arb_wd;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_hi_wr_en_data_arb_we;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_hi_wr_en_data_arb_wr_data;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_hi_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_wkup_thold_lo_cdc_clk_dst_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_thold_lo_cdc_clk_src_i;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_lo_cdc_dst_ds_i;  /* 32-bit */
    uint32_t u_reg_u_wkup_thold_lo_cdc_dst_qs_i;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_lo_cdc_dst_re_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_thold_lo_cdc_dst_regwen_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_thold_lo_cdc_dst_update_i;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_lo_cdc_dst_wd_o;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_lo_cdc_dst_we_o;  /* 1-bit */
    uint8_t u_reg_u_wkup_thold_lo_cdc_rst_dst_ni;  /* 1-bit */
    uint8_t u_reg_u_wkup_thold_lo_cdc_rst_src_ni;  /* 1-bit */
    uint8_t u_reg_u_wkup_thold_lo_cdc_src_busy_o;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_lo_cdc_src_qs_o;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_lo_cdc_src_re_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_thold_lo_cdc_src_regwen_i;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_lo_cdc_src_wd_i;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_lo_cdc_src_we_i;  /* 1-bit */
    uint8_t u_reg_u_wkup_thold_lo_clk_i;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_lo_d;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_lo_de;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_lo_ds;  /* 32-bit */
    uint32_t u_reg_u_wkup_thold_lo_q;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_lo_qe;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_lo_qs;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_lo_rst_ni;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_lo_wd;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_lo_we;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_lo_wr_data;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_lo_wr_en;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_lo_wr_en_data_arb_d;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_lo_wr_en_data_arb_de;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_lo_wr_en_data_arb_q;  /* 32-bit */
    uint32_t u_reg_u_wkup_thold_lo_wr_en_data_arb_wd;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_lo_wr_en_data_arb_we;  /* 1-bit */
    uint32_t u_reg_u_wkup_thold_lo_wr_en_data_arb_wr_data;  /* 32-bit */
    uint8_t u_reg_u_wkup_thold_lo_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_wdog_bark_thold_busy;  /* 1-bit */
    uint32_t u_reg_wdog_bark_thold_qs;  /* 32-bit */
    uint8_t u_reg_wdog_bark_thold_we;  /* 1-bit */
    uint8_t u_reg_wdog_bite_thold_busy;  /* 1-bit */
    uint32_t u_reg_wdog_bite_thold_qs;  /* 32-bit */
    uint8_t u_reg_wdog_bite_thold_we;  /* 1-bit */
    uint8_t u_reg_wdog_count_busy;  /* 1-bit */
    uint8_t u_reg_wdog_count_flds_we;  /* 1-bit */
    uint32_t u_reg_wdog_count_qs;  /* 32-bit */
    uint8_t u_reg_wdog_count_we;  /* 1-bit */
    uint8_t u_reg_wdog_ctrl_busy;  /* 1-bit */
    uint8_t u_reg_wdog_ctrl_qs;  /* 2-bit */
    uint8_t u_reg_wdog_ctrl_we;  /* 1-bit */
    uint8_t u_reg_wdog_regwen_qs;  /* 1-bit */
    uint8_t u_reg_wdog_regwen_we;  /* 1-bit */
    uint8_t u_reg_wkup_cause_busy;  /* 1-bit */
    uint8_t u_reg_wkup_cause_flds_we;  /* 1-bit */
    uint8_t u_reg_wkup_cause_qs;  /* 1-bit */
    uint8_t u_reg_wkup_cause_we;  /* 1-bit */
    uint8_t u_reg_wkup_count_hi_busy;  /* 1-bit */
    uint8_t u_reg_wkup_count_hi_flds_we;  /* 1-bit */
    uint32_t u_reg_wkup_count_hi_qs;  /* 32-bit */
    uint8_t u_reg_wkup_count_hi_we;  /* 1-bit */
    uint8_t u_reg_wkup_count_lo_busy;  /* 1-bit */
    uint8_t u_reg_wkup_count_lo_flds_we;  /* 1-bit */
    uint32_t u_reg_wkup_count_lo_qs;  /* 32-bit */
    uint8_t u_reg_wkup_count_lo_we;  /* 1-bit */
    uint8_t u_reg_wkup_ctrl_busy;  /* 1-bit */
    uint8_t u_reg_wkup_ctrl_flds_we;  /* 2-bit */
    uint16_t u_reg_wkup_ctrl_qs;  /* 13-bit */
    uint8_t u_reg_wkup_ctrl_we;  /* 1-bit */
    uint8_t u_reg_wkup_thold_hi_busy;  /* 1-bit */
    uint32_t u_reg_wkup_thold_hi_qs;  /* 32-bit */
    uint8_t u_reg_wkup_thold_hi_we;  /* 1-bit */
    uint8_t u_reg_wkup_thold_lo_busy;  /* 1-bit */
    uint32_t u_reg_wkup_thold_lo_qs;  /* 32-bit */
    uint8_t u_reg_wkup_thold_lo_we;  /* 1-bit */
    uint8_t u_reg_wr_err;  /* 1-bit */
    uint8_t u_sync_sleep_mode_clk_i;  /* 1-bit */
    uint8_t u_sync_sleep_mode_d_i;  /* 1-bit */
    uint8_t u_sync_sleep_mode_d_o;  /* 1-bit */
    uint8_t u_sync_sleep_mode_q_o;  /* 1-bit */
    uint8_t u_sync_sleep_mode_rst_ni;  /* 1-bit */
    uint8_t u_sync_sleep_mode_u_sync_1_clk_i;  /* 1-bit */
    uint8_t u_sync_sleep_mode_u_sync_1_d_i;  /* 1-bit */
    uint8_t u_sync_sleep_mode_u_sync_1_q_o;  /* 1-bit */
    uint8_t u_sync_sleep_mode_u_sync_1_rst_ni;  /* 1-bit */
    uint8_t u_sync_sleep_mode_u_sync_2_clk_i;  /* 1-bit */
    uint8_t u_sync_sleep_mode_u_sync_2_d_i;  /* 1-bit */
    uint8_t u_sync_sleep_mode_u_sync_2_q_o;  /* 1-bit */
    uint8_t u_sync_sleep_mode_u_sync_2_rst_ni;  /* 1-bit */
    uint8_t wkup_req_o;  /* 1-bit */

    uint8_t _qp_pump;  /* pump pulse: accumulate-ring step enable */
    void (*_qp_before_tick)(void *ctx);
    void *_qp_before_tick_ctx;
    void (*_qp_on_tick)(void *ctx);  /* per-clock observer hook (organs) */
    void *_qp_on_tick_ctx;
    uint8_t  _qp_rewound;      /* organ restored a state snapshot this clock */
    uint8_t  _qp_hold_settle;  /* organ mid-unit: keep settling (bounded) */
    uint8_t  _qp_busy;         /* inside settle: re-entrant inputs latch only */
    int (*_qp_settle_hook)(void *ctx);  /* machine co-step escape hatch:
     * called once per settle iteration; return nonzero while a
     * cross-model transaction involving this model is in flight
     * (keeps the loop alive past a local fixed point and widens
     * the budget).  NULL (the calloc default) = old semantics. */
    void *_qp_settle_hook_ctx;
    uint8_t  _qp_rd_cap;       /* read: response captured on its d_valid tick */
    uint32_t _qp_rd_capv;
    uint32_t _qp_access_gen;   /* bumped by every MMIO entry (snapshot validity) */
    uint8_t  _qp_in_request;   /* the bus request clock is being presented (transient inputs) */
} aon_timer_state;

/* Public API: bridge entrypoints for embedding in a shim device. */
uint64_t aon_timer_read(void *opaque, hwaddr addr, unsigned size);
void     aon_timer_write(void *opaque, hwaddr addr,
                 uint64_t value, unsigned size);
/* Asserts rst_ni for one settle round, then releases — primes the
 * model so registers with non-zero RESVALs see their reset value. */
void aon_timer_reset(aon_timer_state *s);
/* Run the model to quiescence without a bus access (external event
 * sources — SPI pumps, pin changes — call this after poking inputs). */
void aon_timer_settle(aon_timer_state *s);

void aon_timer_step(aon_timer_state *s);
void aon_timer_update(aon_timer_state *s);
void aon_timer_tick(aon_timer_state *s);

void aon_timer_step_many(aon_timer_state *s, unsigned count);

/* Advance one virtual-time tick: bump free-running counters + settle
 * one round (counter->tick->writeback).  Driven by the shim pump. */
void aon_timer_advance_tick(aon_timer_state *s);

/* Phase 2.d input setters — bridge host-side QEMU events into
 * the simulated device.  Each writes one input-port leaf field
 * and runs update_state→tick→update_state to settle.
 */
void aon_timer_set_clk_aon_i(aon_timer_state *s, uint8_t value);
void aon_timer_set_rst_aon_ni(aon_timer_state *s, uint8_t value);
void aon_timer_set_alert_rx_i_0__ping_p(aon_timer_state *s, uint8_t value);
void aon_timer_set_alert_rx_i_0__ping_n(aon_timer_state *s, uint8_t value);
void aon_timer_set_alert_rx_i_0__ack_p(aon_timer_state *s, uint8_t value);
void aon_timer_set_alert_rx_i_0__ack_n(aon_timer_state *s, uint8_t value);
void aon_timer_set_racl_policies_i_0__write_perm(aon_timer_state *s, uint8_t value);
void aon_timer_set_racl_policies_i_0__read_perm(aon_timer_state *s, uint8_t value);
void aon_timer_set_lc_escalate_en_i(aon_timer_state *s, uint8_t value);
void aon_timer_set_sleep_mode_i(aon_timer_state *s, uint8_t value);

#endif /* AON_TIMER_H */
