#ifndef RV_TIMER_H
#define RV_TIMER_H

#include "hw/sysbus.h"
#include "qom/object.h"

#define TYPE_RV_TIMER "rv_timer"
#define RV_TIMER(obj) OBJECT_CHECK(rv_timer_state, (obj), TYPE_RV_TIMER)

typedef struct {
    /* <private> */
    SysBusDevice parent_obj;

    /* <public> */
    MemoryRegion mmio;

    /* ---- Bus Interface Ports (BIP) ---- */
    /* These signals bridge QEMU MMIO and internal logic. */
    uint32_t reg_rdata_next;  /* BIP, 32-bit */
    uint8_t reg_we;  /* BIP, 1-bit */
    uint32_t tl_i_a_address;  /* BIP, 32-bit */
    uint8_t tl_i_a_user_instr_type;  /* BIP, 4-bit */
    uint32_t u_reg_if_wdata_o;  /* BIP, 32-bit */

    /* ---- Internal state registers ---- */
    uint8_t active;  /* 1-bit */
    uint8_t alert_rx_i_0__ack_n;  /* 1-bit */
    uint8_t alert_rx_i_0__ack_p;  /* 1-bit */
    uint8_t alert_rx_i_0__ping_n;  /* 1-bit */
    uint8_t alert_rx_i_0__ping_p;  /* 1-bit */
    uint8_t alert_tx_o_0__alert_n;  /* 1-bit */
    uint8_t alert_tx_o_0__alert_p;  /* 1-bit */
    uint8_t alerts;  /* 1-bit */
    uint8_t clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_ack_level;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_ack_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_clr;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_nd;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_pd;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_req_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_rx_i_ack_n;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_rx_i_ack_p;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_rx_i_ping_n;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_rx_i_ping_p;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_set_d;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_set_q;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_state_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_test_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_test_set_d;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_test_set_q;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_test_trigger;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_trigger;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_tx_o_alert_n;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_alert_tx_o_alert_p;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_ping_clr;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_ping_set_d;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_ping_set_q;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_ping_trigger;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_sigint_detected;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_state_d;  /* 3-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_state_q;  /* 3-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_diff_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_diff_pi;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_event_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_fall_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_diff_check_ok;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_diff_n_edge;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_diff_nd;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_diff_nq;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_diff_p_edge;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_diff_pd;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_diff_pq;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_d_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_u_sync_1_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_u_sync_1_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_u_sync_1_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_u_sync_1_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_u_sync_2_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_u_sync_2_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_u_sync_2_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_n_u_sync_2_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_d_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_u_sync_1_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_u_sync_1_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_u_sync_1_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_u_sync_1_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_u_sync_2_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_u_sync_2_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_u_sync_2_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_i_sync_p_u_sync_2_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_level;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_skew_cnt_d;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_skew_cnt_q;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_state_d;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_gen_async_state_q;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_level_d;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_level_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_level_q;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_rise_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ack_sigint_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_diff_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_diff_pi;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_event_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_fall_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_diff_check_ok;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_diff_n_edge;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_diff_nd;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_diff_nq;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_diff_p_edge;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_diff_pd;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_diff_pq;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_d_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_u_sync_1_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_u_sync_1_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_u_sync_1_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_u_sync_1_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_u_sync_2_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_u_sync_2_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_u_sync_2_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_n_u_sync_2_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_d_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_u_sync_1_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_u_sync_1_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_u_sync_1_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_u_sync_1_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_u_sync_2_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_u_sync_2_d_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_u_sync_2_q_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_i_sync_p_u_sync_2_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_level;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_skew_cnt_d;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_skew_cnt_q;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_state_d;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_gen_async_state_q;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_level_d;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_level_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_level_q;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_rise_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_decode_ping_sigint_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_ack_in_i;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_ack_out_o;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_ack_u_secure_anchor_buf_in_i;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_ack_u_secure_anchor_buf_out_o;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_in_req_in_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_in_req_out_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_in_req_u_secure_anchor_buf_in_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_in_req_u_secure_anchor_buf_out_o;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_ping_in_i;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_ping_out_o;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_ping_u_secure_anchor_buf_in_i;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_buf_ping_u_secure_anchor_buf_out_o;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_flop_alert_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_flop_alert_d_i;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_flop_alert_q_o;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_flop_alert_rst_ni;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_flop_alert_u_secure_anchor_flop_clk_i;  /* 1-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_flop_alert_u_secure_anchor_flop_d_i;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_flop_alert_u_secure_anchor_flop_q_o;  /* 2-bit */
    uint8_t gen_alert_tx_0_u_prim_alert_sender_u_prim_flop_alert_u_secure_anchor_flop_rst_ni;  /* 1-bit */
    uint8_t gen_harts_0_u_core_active;  /* 1-bit */
    uint8_t gen_harts_0_u_core_clk_i;  /* 1-bit */
    uint8_t gen_harts_0_u_core_intr;  /* 1-bit */
    uint64_t gen_harts_0_u_core_mtime;  /* 64-bit */
    uint64_t gen_harts_0_u_core_mtime_d;  /* 64-bit */
    uint64_t gen_harts_0_u_core_mtimecmp_0_;  /* 64-bit */
    uint16_t gen_harts_0_u_core_prescaler;  /* 12-bit */
    uint8_t gen_harts_0_u_core_rst_ni;  /* 1-bit */
    uint8_t gen_harts_0_u_core_step;  /* 8-bit */
    uint8_t gen_harts_0_u_core_tick;  /* 1-bit */
    uint16_t gen_harts_0_u_core_tick_count;  /* 12-bit */
    uint8_t gen_harts_0_u_intr_hw_clk_i;  /* 1-bit */
    uint8_t gen_harts_0_u_intr_hw_event_intr_i;  /* 1-bit */
    uint8_t gen_harts_0_u_intr_hw_hw2reg_intr_state_d_o;  /* 1-bit */
    uint8_t gen_harts_0_u_intr_hw_hw2reg_intr_state_de_o;  /* 1-bit */
    uint8_t gen_harts_0_u_intr_hw_intr_o;  /* 1-bit */
    uint8_t gen_harts_0_u_intr_hw_reg2hw_intr_enable_q_i;  /* 1-bit */
    uint8_t gen_harts_0_u_intr_hw_reg2hw_intr_state_q_i;  /* 1-bit */
    uint8_t gen_harts_0_u_intr_hw_reg2hw_intr_test_q_i;  /* 1-bit */
    uint8_t gen_harts_0_u_intr_hw_reg2hw_intr_test_qe_i;  /* 1-bit */
    uint8_t gen_harts_0_u_intr_hw_rst_ni;  /* 1-bit */
    uint8_t gen_harts_0_u_intr_hw_status;  /* 1-bit */
    uint8_t hw2reg_intr_state0_0__d;  /* 1-bit */
    uint8_t hw2reg_intr_state0_0__de;  /* 1-bit */
    uint32_t hw2reg_timer_v_lower0_d;  /* 32-bit */
    uint8_t hw2reg_timer_v_lower0_de;  /* 1-bit */
    uint32_t hw2reg_timer_v_upper0_d;  /* 32-bit */
    uint8_t hw2reg_timer_v_upper0_de;  /* 1-bit */
    uint8_t intr_out;  /* 1-bit */
    uint8_t intr_timer_expired_hart0_timer0_o;  /* 1-bit */
    uint8_t intr_timer_set;  /* 1-bit */
    uint8_t intr_timer_state_d;  /* 1-bit */
    uint64_t mtime_0_;  /* 64-bit */
    uint64_t mtime_d_0_;  /* 64-bit */
    uint8_t mtimecmp_update_0__0_;  /* 1-bit */
    uint8_t racl_error_o_ctn_uid;  /* 1-bit */
    uint8_t racl_error_o_overflow;  /* 1-bit */
    uint8_t racl_error_o_racl_role;  /* 1-bit */
    uint8_t racl_error_o_read_access;  /* 1-bit */
    uint32_t racl_error_o_request_address;  /* 32-bit */
    uint8_t racl_error_o_valid;  /* 1-bit */
    uint8_t racl_policies_i_0__read_perm;  /* 2-bit */
    uint8_t racl_policies_i_0__write_perm;  /* 2-bit */
    uint8_t rst_ni;  /* 1-bit */
    uint8_t tick;  /* 1-bit */
    uint32_t tl_i_a_data;  /* 32-bit */
    uint8_t tl_i_a_mask;  /* 4-bit */
    uint8_t tl_i_a_opcode;  /* 3-bit */
    uint8_t tl_i_a_param;  /* 3-bit */
    uint8_t tl_i_a_size;  /* 2-bit */
    uint8_t tl_i_a_source;  /* 8-bit */
    uint8_t tl_i_a_user_cmd_intg;  /* 7-bit */
    uint8_t tl_i_a_user_data_intg;  /* 7-bit */
    uint8_t tl_i_a_user_rsvd;  /* 5-bit */
    uint8_t tl_i_a_valid;  /* 1-bit */
    uint8_t tl_i_d_ready;  /* 1-bit */
    uint8_t tl_o_a_ready;  /* 1-bit */
    uint32_t tl_o_d_data;  /* 32-bit */
    uint8_t tl_o_d_error;  /* 1-bit */
    uint8_t tl_o_d_opcode;  /* 3-bit */
    uint8_t tl_o_d_param;  /* 3-bit */
    uint8_t tl_o_d_sink;  /* 1-bit */
    uint8_t tl_o_d_size;  /* 2-bit */
    uint8_t tl_o_d_source;  /* 8-bit */
    uint8_t tl_o_d_user_data_intg;  /* 7-bit */
    uint8_t tl_o_d_user_rsp_intg;  /* 7-bit */
    uint8_t tl_o_d_valid;  /* 1-bit */
    uint16_t u_reg_addr_hit;  /* 10-bit */
    uint8_t u_reg_alert_test_flds_we;  /* 1-bit */
    uint8_t u_reg_alert_test_we;  /* 1-bit */
    uint16_t u_reg_cfg0_prescale_qs;  /* 12-bit */
    uint8_t u_reg_cfg0_step_qs;  /* 8-bit */
    uint8_t u_reg_cfg0_we;  /* 1-bit */
    uint8_t u_reg_clk_i;  /* 1-bit */
    uint8_t u_reg_compare_lower0_0_flds_we;  /* 1-bit */
    uint32_t u_reg_compare_lower0_0_qs;  /* 32-bit */
    uint8_t u_reg_compare_lower0_0_we;  /* 1-bit */
    uint8_t u_reg_compare_upper0_0_flds_we;  /* 1-bit */
    uint32_t u_reg_compare_upper0_0_qs;  /* 32-bit */
    uint8_t u_reg_compare_upper0_0_we;  /* 1-bit */
    uint8_t u_reg_ctrl_qs;  /* 1-bit */
    uint8_t u_reg_ctrl_we;  /* 1-bit */
    uint8_t u_reg_err_q;  /* 1-bit */
    uint8_t u_reg_hw2reg_intr_state0_0__d;  /* 1-bit */
    uint8_t u_reg_hw2reg_intr_state0_0__de;  /* 1-bit */
    uint32_t u_reg_hw2reg_timer_v_lower0_d;  /* 32-bit */
    uint8_t u_reg_hw2reg_timer_v_lower0_de;  /* 1-bit */
    uint32_t u_reg_hw2reg_timer_v_upper0_d;  /* 32-bit */
    uint8_t u_reg_hw2reg_timer_v_upper0_de;  /* 1-bit */
    uint8_t u_reg_intg_err;  /* 1-bit */
    uint8_t u_reg_intg_err_o;  /* 1-bit */
    uint8_t u_reg_intr_enable0_qs;  /* 1-bit */
    uint8_t u_reg_intr_enable0_we;  /* 1-bit */
    uint8_t u_reg_intr_state0_qs;  /* 1-bit */
    uint8_t u_reg_intr_state0_we;  /* 1-bit */
    uint8_t u_reg_intr_test0_flds_we;  /* 1-bit */
    uint8_t u_reg_intr_test0_we;  /* 1-bit */
    uint16_t u_reg_racl_addr_hit_read;  /* 10-bit */
    uint16_t u_reg_racl_addr_hit_write;  /* 10-bit */
    uint8_t u_reg_racl_error_o_ctn_uid;  /* 1-bit */
    uint8_t u_reg_racl_error_o_overflow;  /* 1-bit */
    uint8_t u_reg_racl_error_o_racl_role;  /* 1-bit */
    uint8_t u_reg_racl_error_o_read_access;  /* 1-bit */
    uint32_t u_reg_racl_error_o_request_address;  /* 32-bit */
    uint8_t u_reg_racl_error_o_valid;  /* 1-bit */
    uint8_t u_reg_racl_policies_i_0__read_perm;  /* 2-bit */
    uint8_t u_reg_racl_policies_i_0__write_perm;  /* 2-bit */
    uint8_t u_reg_racl_role_vec;  /* 2-bit */
    uint8_t u_reg_reg2hw_alert_test_q;  /* 1-bit */
    uint8_t u_reg_reg2hw_alert_test_qe;  /* 1-bit */
    uint16_t u_reg_reg2hw_cfg0_prescale_q;  /* 12-bit */
    uint8_t u_reg_reg2hw_cfg0_step_q;  /* 8-bit */
    uint32_t u_reg_reg2hw_compare_lower0_0_q;  /* 32-bit */
    uint8_t u_reg_reg2hw_compare_lower0_0_qe;  /* 1-bit */
    uint32_t u_reg_reg2hw_compare_upper0_0_q;  /* 32-bit */
    uint8_t u_reg_reg2hw_compare_upper0_0_qe;  /* 1-bit */
    uint8_t u_reg_reg2hw_ctrl_0__q;  /* 1-bit */
    uint8_t u_reg_reg2hw_intr_enable0_0__q;  /* 1-bit */
    uint8_t u_reg_reg2hw_intr_state0_0__q;  /* 1-bit */
    uint8_t u_reg_reg2hw_intr_test0_0__q;  /* 1-bit */
    uint8_t u_reg_reg2hw_intr_test0_0__qe;  /* 1-bit */
    uint32_t u_reg_reg2hw_timer_v_lower0_q;  /* 32-bit */
    uint32_t u_reg_reg2hw_timer_v_upper0_q;  /* 32-bit */
    uint16_t u_reg_reg_addr;  /* 9-bit */
    uint8_t u_reg_reg_be;  /* 4-bit */
    uint32_t u_reg_reg_rdata_next;  /* 32-bit */
    uint8_t u_reg_reg_we;  /* 1-bit */
    uint16_t u_reg_reg_we_check;  /* 10-bit */
    uint8_t u_reg_reg_we_err;  /* 1-bit */
    uint8_t u_reg_rst_ni;  /* 1-bit */
    uint32_t u_reg_timer_v_lower0_qs;  /* 32-bit */
    uint8_t u_reg_timer_v_lower0_we;  /* 1-bit */
    uint32_t u_reg_timer_v_upper0_qs;  /* 32-bit */
    uint8_t u_reg_timer_v_upper0_we;  /* 1-bit */
    uint32_t u_reg_tl_i_a_address;  /* 32-bit */
    uint32_t u_reg_tl_i_a_data;  /* 32-bit */
    uint8_t u_reg_tl_i_a_mask;  /* 4-bit */
    uint8_t u_reg_tl_i_a_opcode;  /* 3-bit */
    uint8_t u_reg_tl_i_a_param;  /* 3-bit */
    uint8_t u_reg_tl_i_a_size;  /* 2-bit */
    uint8_t u_reg_tl_i_a_source;  /* 8-bit */
    uint8_t u_reg_tl_i_a_user_cmd_intg;  /* 7-bit */
    uint8_t u_reg_tl_i_a_user_data_intg;  /* 7-bit */
    uint8_t u_reg_tl_i_a_user_instr_type;  /* 4-bit */
    uint8_t u_reg_tl_i_a_user_rsvd;  /* 5-bit */
    uint8_t u_reg_tl_i_a_valid;  /* 1-bit */
    uint8_t u_reg_tl_i_d_ready;  /* 1-bit */
    uint8_t u_reg_tl_o_a_ready;  /* 1-bit */
    uint32_t u_reg_tl_o_d_data;  /* 32-bit */
    uint8_t u_reg_tl_o_d_error;  /* 1-bit */
    uint8_t u_reg_tl_o_d_opcode;  /* 3-bit */
    uint8_t u_reg_tl_o_d_param;  /* 3-bit */
    uint8_t u_reg_tl_o_d_sink;  /* 1-bit */
    uint8_t u_reg_tl_o_d_size;  /* 2-bit */
    uint8_t u_reg_tl_o_d_source;  /* 8-bit */
    uint8_t u_reg_tl_o_d_user_data_intg;  /* 7-bit */
    uint8_t u_reg_tl_o_d_user_rsp_intg;  /* 7-bit */
    uint8_t u_reg_tl_o_d_valid;  /* 1-bit */
    uint8_t u_reg_u_alert_test_d;  /* 1-bit */
    uint8_t u_reg_u_alert_test_ds;  /* 1-bit */
    uint8_t u_reg_u_alert_test_q;  /* 1-bit */
    uint8_t u_reg_u_alert_test_qe;  /* 1-bit */
    uint8_t u_reg_u_alert_test_qre;  /* 1-bit */
    uint8_t u_reg_u_alert_test_qs;  /* 1-bit */
    uint8_t u_reg_u_alert_test_re;  /* 1-bit */
    uint8_t u_reg_u_alert_test_wd;  /* 1-bit */
    uint8_t u_reg_u_alert_test_we;  /* 1-bit */
    uint8_t u_reg_u_cfg0_prescale_clk_i;  /* 1-bit */
    uint16_t u_reg_u_cfg0_prescale_d;  /* 12-bit */
    uint8_t u_reg_u_cfg0_prescale_de;  /* 1-bit */
    uint16_t u_reg_u_cfg0_prescale_ds;  /* 12-bit */
    uint16_t u_reg_u_cfg0_prescale_q;  /* 12-bit */
    uint8_t u_reg_u_cfg0_prescale_qe;  /* 1-bit */
    uint16_t u_reg_u_cfg0_prescale_qs;  /* 12-bit */
    uint8_t u_reg_u_cfg0_prescale_rst_ni;  /* 1-bit */
    uint16_t u_reg_u_cfg0_prescale_wd;  /* 12-bit */
    uint8_t u_reg_u_cfg0_prescale_we;  /* 1-bit */
    uint16_t u_reg_u_cfg0_prescale_wr_data;  /* 12-bit */
    uint8_t u_reg_u_cfg0_prescale_wr_en;  /* 1-bit */
    uint16_t u_reg_u_cfg0_prescale_wr_en_data_arb_d;  /* 12-bit */
    uint8_t u_reg_u_cfg0_prescale_wr_en_data_arb_de;  /* 1-bit */
    uint16_t u_reg_u_cfg0_prescale_wr_en_data_arb_q;  /* 12-bit */
    uint16_t u_reg_u_cfg0_prescale_wr_en_data_arb_wd;  /* 12-bit */
    uint8_t u_reg_u_cfg0_prescale_wr_en_data_arb_we;  /* 1-bit */
    uint16_t u_reg_u_cfg0_prescale_wr_en_data_arb_wr_data;  /* 12-bit */
    uint8_t u_reg_u_cfg0_prescale_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_cfg0_step_clk_i;  /* 1-bit */
    uint8_t u_reg_u_cfg0_step_d;  /* 8-bit */
    uint8_t u_reg_u_cfg0_step_de;  /* 1-bit */
    uint8_t u_reg_u_cfg0_step_ds;  /* 8-bit */
    uint8_t u_reg_u_cfg0_step_q;  /* 8-bit */
    uint8_t u_reg_u_cfg0_step_qe;  /* 1-bit */
    uint8_t u_reg_u_cfg0_step_qs;  /* 8-bit */
    uint8_t u_reg_u_cfg0_step_rst_ni;  /* 1-bit */
    uint8_t u_reg_u_cfg0_step_wd;  /* 8-bit */
    uint8_t u_reg_u_cfg0_step_we;  /* 1-bit */
    uint8_t u_reg_u_cfg0_step_wr_data;  /* 8-bit */
    uint8_t u_reg_u_cfg0_step_wr_en;  /* 1-bit */
    uint8_t u_reg_u_cfg0_step_wr_en_data_arb_d;  /* 8-bit */
    uint8_t u_reg_u_cfg0_step_wr_en_data_arb_de;  /* 1-bit */
    uint8_t u_reg_u_cfg0_step_wr_en_data_arb_q;  /* 8-bit */
    uint8_t u_reg_u_cfg0_step_wr_en_data_arb_wd;  /* 8-bit */
    uint8_t u_reg_u_cfg0_step_wr_en_data_arb_we;  /* 1-bit */
    uint8_t u_reg_u_cfg0_step_wr_en_data_arb_wr_data;  /* 8-bit */
    uint8_t u_reg_u_cfg0_step_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_chk_err_o;  /* 1-bit */
    uint32_t u_reg_u_chk_tl_i_a_address;  /* 32-bit */
    uint32_t u_reg_u_chk_tl_i_a_data;  /* 32-bit */
    uint8_t u_reg_u_chk_tl_i_a_mask;  /* 4-bit */
    uint8_t u_reg_u_chk_tl_i_a_opcode;  /* 3-bit */
    uint8_t u_reg_u_chk_tl_i_a_param;  /* 3-bit */
    uint8_t u_reg_u_chk_tl_i_a_size;  /* 2-bit */
    uint8_t u_reg_u_chk_tl_i_a_source;  /* 8-bit */
    uint8_t u_reg_u_chk_tl_i_a_user_cmd_intg;  /* 7-bit */
    uint8_t u_reg_u_chk_tl_i_a_user_data_intg;  /* 7-bit */
    uint8_t u_reg_u_chk_tl_i_a_user_instr_type;  /* 4-bit */
    uint8_t u_reg_u_chk_tl_i_a_user_rsvd;  /* 5-bit */
    uint8_t u_reg_u_chk_tl_i_a_valid;  /* 1-bit */
    uint8_t u_reg_u_chk_tl_i_d_ready;  /* 1-bit */
    uint8_t u_reg_u_compare_lower0_00_qe_clk_i;  /* 1-bit */
    uint8_t u_reg_u_compare_lower0_00_qe_d_i;  /* 1-bit */
    uint8_t u_reg_u_compare_lower0_00_qe_q_o;  /* 1-bit */
    uint8_t u_reg_u_compare_lower0_00_qe_rst_ni;  /* 1-bit */
    uint8_t u_reg_u_compare_lower0_0_clk_i;  /* 1-bit */
    uint32_t u_reg_u_compare_lower0_0_d;  /* 32-bit */
    uint8_t u_reg_u_compare_lower0_0_de;  /* 1-bit */
    uint32_t u_reg_u_compare_lower0_0_ds;  /* 32-bit */
    uint32_t u_reg_u_compare_lower0_0_q;  /* 32-bit */
    uint8_t u_reg_u_compare_lower0_0_qe;  /* 1-bit */
    uint32_t u_reg_u_compare_lower0_0_qs;  /* 32-bit */
    uint8_t u_reg_u_compare_lower0_0_rst_ni;  /* 1-bit */
    uint32_t u_reg_u_compare_lower0_0_wd;  /* 32-bit */
    uint8_t u_reg_u_compare_lower0_0_we;  /* 1-bit */
    uint32_t u_reg_u_compare_lower0_0_wr_data;  /* 32-bit */
    uint8_t u_reg_u_compare_lower0_0_wr_en;  /* 1-bit */
    uint32_t u_reg_u_compare_lower0_0_wr_en_data_arb_d;  /* 32-bit */
    uint8_t u_reg_u_compare_lower0_0_wr_en_data_arb_de;  /* 1-bit */
    uint32_t u_reg_u_compare_lower0_0_wr_en_data_arb_q;  /* 32-bit */
    uint32_t u_reg_u_compare_lower0_0_wr_en_data_arb_wd;  /* 32-bit */
    uint8_t u_reg_u_compare_lower0_0_wr_en_data_arb_we;  /* 1-bit */
    uint32_t u_reg_u_compare_lower0_0_wr_en_data_arb_wr_data;  /* 32-bit */
    uint8_t u_reg_u_compare_lower0_0_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_compare_upper0_00_qe_clk_i;  /* 1-bit */
    uint8_t u_reg_u_compare_upper0_00_qe_d_i;  /* 1-bit */
    uint8_t u_reg_u_compare_upper0_00_qe_q_o;  /* 1-bit */
    uint8_t u_reg_u_compare_upper0_00_qe_rst_ni;  /* 1-bit */
    uint8_t u_reg_u_compare_upper0_0_clk_i;  /* 1-bit */
    uint32_t u_reg_u_compare_upper0_0_d;  /* 32-bit */
    uint8_t u_reg_u_compare_upper0_0_de;  /* 1-bit */
    uint32_t u_reg_u_compare_upper0_0_ds;  /* 32-bit */
    uint32_t u_reg_u_compare_upper0_0_q;  /* 32-bit */
    uint8_t u_reg_u_compare_upper0_0_qe;  /* 1-bit */
    uint32_t u_reg_u_compare_upper0_0_qs;  /* 32-bit */
    uint8_t u_reg_u_compare_upper0_0_rst_ni;  /* 1-bit */
    uint32_t u_reg_u_compare_upper0_0_wd;  /* 32-bit */
    uint8_t u_reg_u_compare_upper0_0_we;  /* 1-bit */
    uint32_t u_reg_u_compare_upper0_0_wr_data;  /* 32-bit */
    uint8_t u_reg_u_compare_upper0_0_wr_en;  /* 1-bit */
    uint32_t u_reg_u_compare_upper0_0_wr_en_data_arb_d;  /* 32-bit */
    uint8_t u_reg_u_compare_upper0_0_wr_en_data_arb_de;  /* 1-bit */
    uint32_t u_reg_u_compare_upper0_0_wr_en_data_arb_q;  /* 32-bit */
    uint32_t u_reg_u_compare_upper0_0_wr_en_data_arb_wd;  /* 32-bit */
    uint8_t u_reg_u_compare_upper0_0_wr_en_data_arb_we;  /* 1-bit */
    uint32_t u_reg_u_compare_upper0_0_wr_en_data_arb_wr_data;  /* 32-bit */
    uint8_t u_reg_u_compare_upper0_0_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_ctrl_clk_i;  /* 1-bit */
    uint8_t u_reg_u_ctrl_d;  /* 1-bit */
    uint8_t u_reg_u_ctrl_de;  /* 1-bit */
    uint8_t u_reg_u_ctrl_ds;  /* 1-bit */
    uint8_t u_reg_u_ctrl_q;  /* 1-bit */
    uint8_t u_reg_u_ctrl_qe;  /* 1-bit */
    uint8_t u_reg_u_ctrl_qs;  /* 1-bit */
    uint8_t u_reg_u_ctrl_rst_ni;  /* 1-bit */
    uint8_t u_reg_u_ctrl_wd;  /* 1-bit */
    uint8_t u_reg_u_ctrl_we;  /* 1-bit */
    uint8_t u_reg_u_ctrl_wr_data;  /* 1-bit */
    uint8_t u_reg_u_ctrl_wr_en;  /* 1-bit */
    uint8_t u_reg_u_ctrl_wr_en_data_arb_d;  /* 1-bit */
    uint8_t u_reg_u_ctrl_wr_en_data_arb_de;  /* 1-bit */
    uint8_t u_reg_u_ctrl_wr_en_data_arb_q;  /* 1-bit */
    uint8_t u_reg_u_ctrl_wr_en_data_arb_wd;  /* 1-bit */
    uint8_t u_reg_u_ctrl_wr_en_data_arb_we;  /* 1-bit */
    uint8_t u_reg_u_ctrl_wr_en_data_arb_wr_data;  /* 1-bit */
    uint8_t u_reg_u_ctrl_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_intr_enable0_clk_i;  /* 1-bit */
    uint8_t u_reg_u_intr_enable0_d;  /* 1-bit */
    uint8_t u_reg_u_intr_enable0_de;  /* 1-bit */
    uint8_t u_reg_u_intr_enable0_ds;  /* 1-bit */
    uint8_t u_reg_u_intr_enable0_q;  /* 1-bit */
    uint8_t u_reg_u_intr_enable0_qe;  /* 1-bit */
    uint8_t u_reg_u_intr_enable0_qs;  /* 1-bit */
    uint8_t u_reg_u_intr_enable0_rst_ni;  /* 1-bit */
    uint8_t u_reg_u_intr_enable0_wd;  /* 1-bit */
    uint8_t u_reg_u_intr_enable0_we;  /* 1-bit */
    uint8_t u_reg_u_intr_enable0_wr_data;  /* 1-bit */
    uint8_t u_reg_u_intr_enable0_wr_en;  /* 1-bit */
    uint8_t u_reg_u_intr_enable0_wr_en_data_arb_d;  /* 1-bit */
    uint8_t u_reg_u_intr_enable0_wr_en_data_arb_de;  /* 1-bit */
    uint8_t u_reg_u_intr_enable0_wr_en_data_arb_q;  /* 1-bit */
    uint8_t u_reg_u_intr_enable0_wr_en_data_arb_wd;  /* 1-bit */
    uint8_t u_reg_u_intr_enable0_wr_en_data_arb_we;  /* 1-bit */
    uint8_t u_reg_u_intr_enable0_wr_en_data_arb_wr_data;  /* 1-bit */
    uint8_t u_reg_u_intr_enable0_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_intr_state0_clk_i;  /* 1-bit */
    uint8_t u_reg_u_intr_state0_d;  /* 1-bit */
    uint8_t u_reg_u_intr_state0_de;  /* 1-bit */
    uint8_t u_reg_u_intr_state0_ds;  /* 1-bit */
    uint8_t u_reg_u_intr_state0_q;  /* 1-bit */
    uint8_t u_reg_u_intr_state0_qe;  /* 1-bit */
    uint8_t u_reg_u_intr_state0_qs;  /* 1-bit */
    uint8_t u_reg_u_intr_state0_rst_ni;  /* 1-bit */
    uint8_t u_reg_u_intr_state0_wd;  /* 1-bit */
    uint8_t u_reg_u_intr_state0_we;  /* 1-bit */
    uint8_t u_reg_u_intr_state0_wr_data;  /* 1-bit */
    uint8_t u_reg_u_intr_state0_wr_en;  /* 1-bit */
    uint8_t u_reg_u_intr_state0_wr_en_data_arb_d;  /* 1-bit */
    uint8_t u_reg_u_intr_state0_wr_en_data_arb_de;  /* 1-bit */
    uint8_t u_reg_u_intr_state0_wr_en_data_arb_q;  /* 1-bit */
    uint8_t u_reg_u_intr_state0_wr_en_data_arb_wd;  /* 1-bit */
    uint8_t u_reg_u_intr_state0_wr_en_data_arb_we;  /* 1-bit */
    uint8_t u_reg_u_intr_state0_wr_en_data_arb_wr_data;  /* 1-bit */
    uint8_t u_reg_u_intr_state0_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_intr_test0_d;  /* 1-bit */
    uint8_t u_reg_u_intr_test0_ds;  /* 1-bit */
    uint8_t u_reg_u_intr_test0_q;  /* 1-bit */
    uint8_t u_reg_u_intr_test0_qe;  /* 1-bit */
    uint8_t u_reg_u_intr_test0_qre;  /* 1-bit */
    uint8_t u_reg_u_intr_test0_qs;  /* 1-bit */
    uint8_t u_reg_u_intr_test0_re;  /* 1-bit */
    uint8_t u_reg_u_intr_test0_wd;  /* 1-bit */
    uint8_t u_reg_u_intr_test0_we;  /* 1-bit */
    uint8_t u_reg_u_prim_reg_we_check_clk_i;  /* 1-bit */
    uint8_t u_reg_u_prim_reg_we_check_en_i;  /* 1-bit */
    uint8_t u_reg_u_prim_reg_we_check_err_o;  /* 1-bit */
    uint16_t u_reg_u_prim_reg_we_check_oh_i;  /* 10-bit */
    uint8_t u_reg_u_prim_reg_we_check_rst_ni;  /* 1-bit */
    uint8_t u_reg_u_reg_if_a_ack;  /* 1-bit */
    uint8_t u_reg_u_reg_if_addr_align_err;  /* 1-bit */
    uint16_t u_reg_u_reg_if_addr_o;  /* 9-bit */
    uint8_t u_reg_u_reg_if_be_o;  /* 4-bit */
    uint8_t u_reg_u_reg_if_busy_i;  /* 1-bit */
    uint8_t u_reg_u_reg_if_clk_i;  /* 1-bit */
    uint8_t u_reg_u_reg_if_d_ack;  /* 1-bit */
    uint8_t u_reg_u_reg_if_en_ifetch_i;  /* 4-bit */
    uint8_t u_reg_u_reg_if_err_internal;  /* 1-bit */
    uint8_t u_reg_u_reg_if_error_i;  /* 1-bit */
    uint8_t u_reg_u_reg_if_error_q;  /* 1-bit */
    uint8_t u_reg_u_reg_if_intg_error_o;  /* 1-bit */
    uint8_t u_reg_u_reg_if_outstanding_q;  /* 1-bit */
    uint8_t u_reg_u_reg_if_rd_req;  /* 1-bit */
    uint32_t u_reg_u_reg_if_rdata_i;  /* 32-bit */
    uint32_t u_reg_u_reg_if_rdata_q;  /* 32-bit */
    uint8_t u_reg_u_reg_if_re_o;  /* 1-bit */
    uint8_t u_reg_u_reg_if_reqid_q;  /* 8-bit */
    uint8_t u_reg_u_reg_if_reqsz_q;  /* 2-bit */
    uint8_t u_reg_u_reg_if_rspop_q;  /* 3-bit */
    uint8_t u_reg_u_reg_if_rst_ni;  /* 1-bit */
    uint32_t u_reg_u_reg_if_tl_i_a_address;  /* 32-bit */
    uint32_t u_reg_u_reg_if_tl_i_a_data;  /* 32-bit */
    uint8_t u_reg_u_reg_if_tl_i_a_mask;  /* 4-bit */
    uint8_t u_reg_u_reg_if_tl_i_a_opcode;  /* 3-bit */
    uint8_t u_reg_u_reg_if_tl_i_a_param;  /* 3-bit */
    uint8_t u_reg_u_reg_if_tl_i_a_size;  /* 2-bit */
    uint8_t u_reg_u_reg_if_tl_i_a_source;  /* 8-bit */
    uint8_t u_reg_u_reg_if_tl_i_a_user_cmd_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_tl_i_a_user_data_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_tl_i_a_user_instr_type;  /* 4-bit */
    uint8_t u_reg_u_reg_if_tl_i_a_user_rsvd;  /* 5-bit */
    uint8_t u_reg_u_reg_if_tl_i_a_valid;  /* 1-bit */
    uint8_t u_reg_u_reg_if_tl_i_d_ready;  /* 1-bit */
    uint8_t u_reg_u_reg_if_tl_o_a_ready;  /* 1-bit */
    uint32_t u_reg_u_reg_if_tl_o_d_data;  /* 32-bit */
    uint8_t u_reg_u_reg_if_tl_o_d_error;  /* 1-bit */
    uint8_t u_reg_u_reg_if_tl_o_d_opcode;  /* 3-bit */
    uint8_t u_reg_u_reg_if_tl_o_d_param;  /* 3-bit */
    uint8_t u_reg_u_reg_if_tl_o_d_sink;  /* 1-bit */
    uint8_t u_reg_u_reg_if_tl_o_d_size;  /* 2-bit */
    uint8_t u_reg_u_reg_if_tl_o_d_source;  /* 8-bit */
    uint8_t u_reg_u_reg_if_tl_o_d_user_data_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_tl_o_d_user_rsp_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_tl_o_d_valid;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_err_addr_sz_chk;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_err_clk_i;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_err_err_o;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_err_fulldata_chk;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_err_mask;  /* 4-bit */
    uint8_t u_reg_u_reg_if_u_err_mask_chk;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_err_rst_ni;  /* 1-bit */
    uint32_t u_reg_u_reg_if_u_err_tl_i_a_address;  /* 32-bit */
    uint32_t u_reg_u_reg_if_u_err_tl_i_a_data;  /* 32-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_a_mask;  /* 4-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_a_opcode;  /* 3-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_a_param;  /* 3-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_a_size;  /* 2-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_a_source;  /* 8-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_a_user_cmd_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_a_user_data_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_a_user_instr_type;  /* 4-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_a_user_rsvd;  /* 5-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_a_valid;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_err_tl_i_d_ready;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_data_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_rsp_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_a_ready;  /* 1-bit */
    uint32_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_d_data;  /* 32-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_d_error;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_d_opcode;  /* 3-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_d_param;  /* 3-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_d_sink;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_d_size;  /* 2-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_d_source;  /* 8-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_d_user_data_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_d_user_rsp_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_i_d_valid;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_a_ready;  /* 1-bit */
    uint32_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_d_data;  /* 32-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_d_error;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_d_opcode;  /* 3-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_d_param;  /* 3-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_d_sink;  /* 1-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_d_size;  /* 2-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_d_source;  /* 8-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_d_user_data_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_d_user_rsp_intg;  /* 7-bit */
    uint8_t u_reg_u_reg_if_u_rsp_intg_gen_tl_o_d_valid;  /* 1-bit */
    uint32_t u_reg_u_reg_if_wdata_o;  /* 32-bit */
    uint8_t u_reg_u_reg_if_we_o;  /* 1-bit */
    uint8_t u_reg_u_reg_if_wr_req;  /* 1-bit */
    uint8_t u_reg_u_rsp_intg_gen_data_intg;  /* 7-bit */
    uint32_t u_reg_u_rsp_intg_gen_gen_data_intg_u_tlul_data_integ_enc_data_i;  /* 32-bit */
    uint64_t u_reg_u_rsp_intg_gen_gen_data_intg_u_tlul_data_integ_enc_data_intg_o;  /* 39-bit */
    uint32_t u_reg_u_rsp_intg_gen_gen_data_intg_u_tlul_data_integ_enc_u_data_gen_data_i;  /* 32-bit */
    uint64_t u_reg_u_rsp_intg_gen_gen_data_intg_u_tlul_data_integ_enc_u_data_gen_data_o;  /* 39-bit */
    uint64_t u_reg_u_rsp_intg_gen_gen_rsp_intg_u_rsp_gen_data_i;  /* 57-bit */
    uint64_t u_reg_u_rsp_intg_gen_gen_rsp_intg_u_rsp_gen_data_o;  /* 64-bit */
    uint8_t u_reg_u_rsp_intg_gen_qpinl5_payload_error;  /* 1-bit */
    uint8_t u_reg_u_rsp_intg_gen_qpinl5_payload_opcode;  /* 3-bit */
    uint8_t u_reg_u_rsp_intg_gen_qpinl5_payload_size;  /* 2-bit */
    uint8_t u_reg_u_rsp_intg_gen_rsp_intg;  /* 7-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_i_a_ready;  /* 1-bit */
    uint32_t u_reg_u_rsp_intg_gen_tl_i_d_data;  /* 32-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_i_d_error;  /* 1-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_i_d_opcode;  /* 3-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_i_d_param;  /* 3-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_i_d_sink;  /* 1-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_i_d_size;  /* 2-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_i_d_source;  /* 8-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_i_d_user_data_intg;  /* 7-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_i_d_user_rsp_intg;  /* 7-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_i_d_valid;  /* 1-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_o_a_ready;  /* 1-bit */
    uint32_t u_reg_u_rsp_intg_gen_tl_o_d_data;  /* 32-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_o_d_error;  /* 1-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_o_d_opcode;  /* 3-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_o_d_param;  /* 3-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_o_d_sink;  /* 1-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_o_d_size;  /* 2-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_o_d_source;  /* 8-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_o_d_user_data_intg;  /* 7-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_o_d_user_rsp_intg;  /* 7-bit */
    uint8_t u_reg_u_rsp_intg_gen_tl_o_d_valid;  /* 1-bit */
    uint8_t u_reg_u_timer_v_lower0_clk_i;  /* 1-bit */
    uint32_t u_reg_u_timer_v_lower0_d;  /* 32-bit */
    uint8_t u_reg_u_timer_v_lower0_de;  /* 1-bit */
    uint32_t u_reg_u_timer_v_lower0_ds;  /* 32-bit */
    uint32_t u_reg_u_timer_v_lower0_q;  /* 32-bit */
    uint8_t u_reg_u_timer_v_lower0_qe;  /* 1-bit */
    uint32_t u_reg_u_timer_v_lower0_qs;  /* 32-bit */
    uint8_t u_reg_u_timer_v_lower0_rst_ni;  /* 1-bit */
    uint32_t u_reg_u_timer_v_lower0_wd;  /* 32-bit */
    uint8_t u_reg_u_timer_v_lower0_we;  /* 1-bit */
    uint32_t u_reg_u_timer_v_lower0_wr_data;  /* 32-bit */
    uint8_t u_reg_u_timer_v_lower0_wr_en;  /* 1-bit */
    uint32_t u_reg_u_timer_v_lower0_wr_en_data_arb_d;  /* 32-bit */
    uint8_t u_reg_u_timer_v_lower0_wr_en_data_arb_de;  /* 1-bit */
    uint32_t u_reg_u_timer_v_lower0_wr_en_data_arb_q;  /* 32-bit */
    uint32_t u_reg_u_timer_v_lower0_wr_en_data_arb_wd;  /* 32-bit */
    uint8_t u_reg_u_timer_v_lower0_wr_en_data_arb_we;  /* 1-bit */
    uint32_t u_reg_u_timer_v_lower0_wr_en_data_arb_wr_data;  /* 32-bit */
    uint8_t u_reg_u_timer_v_lower0_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_u_timer_v_upper0_clk_i;  /* 1-bit */
    uint32_t u_reg_u_timer_v_upper0_d;  /* 32-bit */
    uint8_t u_reg_u_timer_v_upper0_de;  /* 1-bit */
    uint32_t u_reg_u_timer_v_upper0_ds;  /* 32-bit */
    uint32_t u_reg_u_timer_v_upper0_q;  /* 32-bit */
    uint8_t u_reg_u_timer_v_upper0_qe;  /* 1-bit */
    uint32_t u_reg_u_timer_v_upper0_qs;  /* 32-bit */
    uint8_t u_reg_u_timer_v_upper0_rst_ni;  /* 1-bit */
    uint32_t u_reg_u_timer_v_upper0_wd;  /* 32-bit */
    uint8_t u_reg_u_timer_v_upper0_we;  /* 1-bit */
    uint32_t u_reg_u_timer_v_upper0_wr_data;  /* 32-bit */
    uint8_t u_reg_u_timer_v_upper0_wr_en;  /* 1-bit */
    uint32_t u_reg_u_timer_v_upper0_wr_en_data_arb_d;  /* 32-bit */
    uint8_t u_reg_u_timer_v_upper0_wr_en_data_arb_de;  /* 1-bit */
    uint32_t u_reg_u_timer_v_upper0_wr_en_data_arb_q;  /* 32-bit */
    uint32_t u_reg_u_timer_v_upper0_wr_en_data_arb_wd;  /* 32-bit */
    uint8_t u_reg_u_timer_v_upper0_wr_en_data_arb_we;  /* 1-bit */
    uint32_t u_reg_u_timer_v_upper0_wr_en_data_arb_wr_data;  /* 32-bit */
    uint8_t u_reg_u_timer_v_upper0_wr_en_data_arb_wr_en;  /* 1-bit */
    uint8_t u_reg_wr_err;  /* 1-bit */

    uint8_t _qp_pump;  /* pump pulse: accumulate-ring step enable */
    void (*_qp_before_tick)(void *ctx);
    void *_qp_before_tick_ctx;
    void (*_qp_on_tick)(void *ctx);  /* per-clock observer hook (organs) */
    void *_qp_on_tick_ctx;
    uint8_t  _qp_rewound;      /* organ restored a state snapshot this clock */
    uint8_t  _qp_hold_settle;  /* organ mid-unit: keep settling (bounded) */
    uint8_t  _qp_busy;         /* inside settle: re-entrant inputs latch only */
    uint32_t _qp_access_gen;   /* bumped by every MMIO entry (snapshot validity) */
    uint8_t  _qp_in_request;   /* the bus request clock is being presented (transient inputs) */
} rv_timer_state;

/* Public API: bridge entrypoints for embedding in a shim device. */
uint64_t rv_timer_read(void *opaque, hwaddr addr, unsigned size);
void     rv_timer_write(void *opaque, hwaddr addr,
                uint64_t value, unsigned size);
/* Asserts rst_ni for one settle round, then releases — primes the
 * model so registers with non-zero RESVALs see their reset value. */
void rv_timer_reset(rv_timer_state *s);
/* Run the model to quiescence without a bus access (external event
 * sources — SPI pumps, pin changes — call this after poking inputs). */
void rv_timer_settle(rv_timer_state *s);

void rv_timer_step(rv_timer_state *s);

void rv_timer_step_many(rv_timer_state *s, unsigned count);

/* Advance one virtual-time tick: bump free-running counters + settle
 * one round (counter->tick->writeback).  Driven by the shim pump. */
void rv_timer_advance_tick(rv_timer_state *s);

/* Phase 2.d input setters — bridge host-side QEMU events into
 * the simulated device.  Each writes one input-port leaf field
 * and runs update_state→tick→update_state to settle.
 */
void rv_timer_set_alert_rx_i_0__ping_p(rv_timer_state *s, uint8_t value);
void rv_timer_set_alert_rx_i_0__ping_n(rv_timer_state *s, uint8_t value);
void rv_timer_set_alert_rx_i_0__ack_p(rv_timer_state *s, uint8_t value);
void rv_timer_set_alert_rx_i_0__ack_n(rv_timer_state *s, uint8_t value);
void rv_timer_set_racl_policies_i_0__write_perm(rv_timer_state *s, uint8_t value);
void rv_timer_set_racl_policies_i_0__read_perm(rv_timer_state *s, uint8_t value);

#endif /* RV_TIMER_H */
